/* soapServer.c
   Generated by gSOAP 2.8.5 from cwmp-1-1.h

Copyright(C) 2000-2011, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) soapServer.c ver 2.8.5 2011-12-14 08:23:26 GMT")

#define COOKIE_DOMAIN "192.168.154.128"
#define COOKIE_PATH "/"

#ifdef WITH_FASTCGI
SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap *soap)
{
#ifndef WITH_FASTCGI
	unsigned int k = soap->max_keep_alive;
#endif
	do
	{
#ifndef WITH_FASTCGI
		if (soap->max_keep_alive > 0 && !--k)
			soap->keep_alive = 0;
#endif
		if (soap_begin_serve(soap))
		{	if (soap->error >= SOAP_STOP)
				continue;
			return soap->error;
		}
		if (soap_serve_request(soap) || (soap->fserveloop && soap->fserveloop(soap)))
		{
#ifdef WITH_FASTCGI
			soap_send_fault(soap);
#else
			return soap_send_fault(soap);
#endif
		}

#ifdef WITH_FASTCGI
		soap_destroy(soap);
		soap_end(soap);
	} while (1);
#else
	} while (soap->keep_alive);
#endif
	return SOAP_OK;
}
#else

/* standalone */
SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap *soap)
{
	unsigned int k = soap->max_keep_alive;

	do
	{
		soap_begin(soap);

		if (soap->max_keep_alive > 0 && !--k)
			soap->keep_alive = 0;

		if (soap_begin_recv(soap))
		{
			if (soap->error < SOAP_STOP && soap->error != SOAP_ZERO_CONTENT)
			{
				return soap_send_empty_response(soap, 204);
			}
			else if(soap->error != SOAP_ZERO_CONTENT) {
				soap_closesock(soap);
				continue;
			}
		}
		
		if (soap->error == SOAP_ZERO_CONTENT 
		 || soap_envelope_begin_in(soap)
		 || soap_recv_header(soap)
		 || soap_body_begin_in(soap)
		 || soap_serve_request(soap)
		 || (soap->fserveloop && soap->fserveloop(soap)))
		{
			if(soap->error != SOAP_NO_TAG && soap->error != SOAP_ZERO_CONTENT)
				return soap_send_fault(soap);
			else {
				soap_serve_request(soap);
			}
		}

		soap_destroy(soap);
		soap_end(soap);
		
	} while (soap->keep_alive);

	soap_closesock(soap);	
	return SOAP_OK;
}
#endif

#ifndef WITH_NOSERVEREQUEST
SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap *soap)
{
	char session[64], *cookie = 0;

	if(soap->error == SOAP_NO_TAG || soap->error == SOAP_ZERO_CONTENT) {
		cookie = soap_cookie_value(soap,"sessionid", NULL, NULL);
		if(!cookie)
			return cwmp__reply_EmptyPost(soap);

		if(!chk_session_valid(soap, cookie))
			return cwmp__reply_EmptyPost(soap);
		
		return cwmp__reply_RPCMessage();
	}
	
	soap_peek_element(soap);

 	if (!soap_match_tag(soap, soap->tag, "cwmp:Inform")) {
		// a new session
		new_session_id(session, 1);
		
		soap_set_cookie(soap, "sessionid", session, NULL, NULL);
		soap_set_cookie_expire(soap, "sessionid", get_cookie_expire(), NULL, NULL);

		session2database(soap, session);
 	}
	else {
		cookie = soap_cookie_value(soap,"sessionid", NULL, NULL);
		if(!cookie)
			return cwmp__reply_EmptyPost(soap);

		
		if(!chk_session_valid(soap, cookie))
			return cwmp__reply_EmptyPost(soap);
	}

	if (!soap_match_tag(soap, soap->tag, "cwmp:GetRPCMethodsResponse"))
		return soap_serve___cwmp__GetRPCMethods(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp:SetParameterValuesResponse"))
		return soap_serve___cwmp__SetParameterValues(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp:GetParameterValuesResponse"))
		return soap_serve___cwmp__GetParameterValues(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp:GetParameterNamesResponse"))
		return soap_serve___cwmp__GetParameterNames(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp:SetParameterAttributesResponse"))
		return soap_serve___cwmp__SetParameterAttributes(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp:GetParameterAttributesResponse"))
		return soap_serve___cwmp__GetParameterAttributes(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp:AddObjectResponse"))
		return soap_serve___cwmp__AddObject(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp:DeleteObjectResponse"))
		return soap_serve___cwmp__DeleteObject(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp:DownloadResponse"))
		return soap_serve___cwmp__Download(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp:RebootResponse"))
		return soap_serve___cwmp__Reboot(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp:GetQueuedTransfersResponse"))
		return soap_serve___cwmp__GetQueuedTransfers(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp:ScheduleInformResponse"))
		return soap_serve___cwmp__ScheduleInform(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp:SetVouchersResponse"))
		return soap_serve___cwmp__SetVouchers(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp:GetOptionsResponse"))
		return soap_serve___cwmp__GetOptions(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp:UploadResponse"))
		return soap_serve___cwmp__Upload(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp:FactoryResetResponse"))
		return soap_serve___cwmp__FactoryReset(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp:GetAllQueuedTransfersResponse"))
		return soap_serve___cwmp__GetAllQueuedTransfers(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp:Inform"))
		return soap_serve___cwmp__Inform(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp:TransferComplete"))
		return soap_serve___cwmp__TransferComplete(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp:AutonomousTransferComplete"))
		return soap_serve___cwmp__AutonomousTransferComplete(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp:Kicked"))
		return soap_serve___cwmp__Kicked(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp:RequestDownload"))
		return soap_serve___cwmp__RequestDownload(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp:Fault"))
		return soap_serve___cwmp__Fault(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp:Fault"))
		return soap_serve___cwmp__EmptyPost(soap);
	return soap->error = SOAP_NO_METHOD;
}
#endif

SOAP_FMAC5 int SOAP_FMAC6 cwmp__reply_GetRPCMethods(struct soap *soap)
{
	struct _cwmp__GetRPCMethods cwmp__GetRPCMethods;

	memset(&cwmp__GetRPCMethods, 0, sizeof(struct _cwmp__GetRPCMethods));

	soap_serializeheader(soap);
	soap_serialize__cwmp__GetRPCMethods(soap, &cwmp__GetRPCMethods);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__cwmp__GetRPCMethods(soap, &cwmp__GetRPCMethods, "cwmp:GetRPCMethods", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__cwmp__GetRPCMethods(soap, &cwmp__GetRPCMethods, "cwmp:GetRPCMethods", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;

	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 cwmp__reply_SetParameterValues(struct soap *soap)
{
	struct _cwmp__SetParameterValues cwmp__SetParameterValues;

	memset(&cwmp__SetParameterValues, 0, sizeof(struct _cwmp__SetParameterValues));

	soap_serializeheader(soap);
	soap_serialize__cwmp__SetParameterValues(soap, &cwmp__SetParameterValues);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__cwmp__SetParameterValues(soap, &cwmp__SetParameterValues, "cwmp:SetParameterValues", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__cwmp__SetParameterValues(soap, &cwmp__SetParameterValues, "cwmp:SetParameterValues", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;

	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 cwmp__reply_GetParameterValues(struct soap *soap)
{
	struct _cwmp__GetParameterValues cwmp__GetParameterValues;

	memset(&cwmp__GetParameterValues, 0, sizeof(struct _cwmp__GetParameterValues));

	soap_serializeheader(soap);
	soap_serialize__cwmp__GetParameterValues(soap, &cwmp__GetParameterValues);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__cwmp__GetParameterValues(soap, &cwmp__GetParameterValues, "cwmp:GetParameterValues", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__cwmp__GetParameterValues(soap, &cwmp__GetParameterValues, "cwmp:GetParameterValues", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;

	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 cwmp__reply_GetParameterNames(struct soap *soap)
{
	struct _cwmp__GetParameterNames cwmp__GetParameterNames;

	memset(&cwmp__GetParameterNames, 0, sizeof(struct _cwmp__GetParameterNames));

	soap_serializeheader(soap);
	soap_serialize__cwmp__GetParameterNames(soap, &cwmp__GetParameterNames);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__cwmp__GetParameterNames(soap, &cwmp__GetParameterNames, "cwmp:GetParameterNames", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__cwmp__GetParameterNames(soap, &cwmp__GetParameterNames, "cwmp:GetParameterNames", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;

	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 cwmp__reply_SetParameterAttributes(struct soap *soap)
{
	struct _cwmp__SetParameterAttributes cwmp__SetParameterAttributes;

	memset(&cwmp__SetParameterAttributes, 0, sizeof(struct _cwmp__SetParameterAttributes));

	soap_serializeheader(soap);
	soap_serialize__cwmp__SetParameterAttributes(soap, &cwmp__SetParameterAttributes);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__cwmp__SetParameterAttributes(soap, &cwmp__SetParameterAttributes, "cwmp:SetParameterAttributes", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__cwmp__SetParameterAttributes(soap, &cwmp__SetParameterAttributes, "cwmp:SetParameterAttributes", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;

	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 cwmp__reply_GetParameterAttributes(struct soap *soap)
{
	struct _cwmp__GetParameterAttributes cwmp__GetParameterAttributes;

	memset(&cwmp__GetParameterAttributes, 0, sizeof(struct _cwmp__GetParameterAttributes));

	soap_serializeheader(soap);
	soap_serialize__cwmp__GetParameterAttributes(soap, &cwmp__GetParameterAttributes);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__cwmp__GetParameterAttributes(soap, &cwmp__GetParameterAttributes, "cwmp:GetParameterAttributes", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__cwmp__GetParameterAttributes(soap, &cwmp__GetParameterAttributes, "cwmp:GetParameterAttributes", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;

	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 cwmp__reply_AddObject(struct soap *soap)
{
	struct _cwmp__AddObject cwmp__AddObject;

	memset(&cwmp__AddObject, 0, sizeof(struct _cwmp__AddObject));

	soap_serializeheader(soap);
	soap_serialize__cwmp__AddObject(soap, &cwmp__AddObject);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__cwmp__AddObject(soap, &cwmp__AddObject, "cwmp:AddObject", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__cwmp__AddObject(soap, &cwmp__AddObject, "cwmp:AddObject", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;

	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 cwmp__reply_DeleteObject(struct soap *soap)
{
	struct _cwmp__DeleteObject cwmp__DeleteObject;

	memset(&cwmp__DeleteObject, 0, sizeof(struct _cwmp__DeleteObject));

	soap_serializeheader(soap);
	soap_serialize__cwmp__DeleteObject(soap, &cwmp__DeleteObject);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__cwmp__DeleteObject(soap, &cwmp__DeleteObject, "cwmp:DeleteObject", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__cwmp__DeleteObject(soap, &cwmp__DeleteObject, "cwmp:DeleteObject", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;

	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 cwmp__reply_Download(struct soap *soap)
{
	struct _cwmp__Download cwmp__Download;

	memset(&cwmp__Download, 0, sizeof(struct _cwmp__Download));

	soap_serializeheader(soap);
	soap_serialize__cwmp__Download(soap, &cwmp__Download);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__cwmp__Download(soap, &cwmp__Download, "cwmp:Download", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__cwmp__Download(soap, &cwmp__Download, "cwmp:Download", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;

	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 cwmp__reply_Reboot(struct soap *soap)
{
	struct _cwmp__Reboot cwmp__Reboot;

	memset(&cwmp__Reboot, 0, sizeof(struct _cwmp__Reboot));

	soap_serializeheader(soap);
	soap_serialize__cwmp__Reboot(soap, &cwmp__Reboot);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__cwmp__Reboot(soap, &cwmp__Reboot, "cwmp:Reboot", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__cwmp__Reboot(soap, &cwmp__Reboot, "cwmp:Reboot", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;

	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 cwmp__reply_GetQueuedTransfers(struct soap *soap)
{
	struct _cwmp__GetQueuedTransfers cwmp__GetQueuedTransfers;

	memset(&cwmp__GetQueuedTransfers, 0, sizeof(struct _cwmp__GetQueuedTransfers));

	soap_serializeheader(soap);
	soap_serialize__cwmp__GetQueuedTransfers(soap, &cwmp__GetQueuedTransfers);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__cwmp__GetQueuedTransfers(soap, &cwmp__GetQueuedTransfers, "cwmp:GetQueuedTransfers", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__cwmp__GetQueuedTransfers(soap, &cwmp__GetQueuedTransfers, "cwmp:GetQueuedTransfers", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;

	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 cwmp__reply_ScheduleInform(struct soap *soap)
{
	struct _cwmp__ScheduleInform cwmp__ScheduleInform;

	memset(&cwmp__ScheduleInform, 0, sizeof(struct _cwmp__ScheduleInform));

	soap_serializeheader(soap);
	soap_serialize__cwmp__ScheduleInform(soap, &cwmp__ScheduleInform);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__cwmp__ScheduleInform(soap, &cwmp__ScheduleInform, "cwmp:ScheduleInform", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__cwmp__ScheduleInform(soap, &cwmp__ScheduleInform, "cwmp:ScheduleInform", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;

	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 cwmp__reply_SetVouchers(struct soap *soap)
{
	struct _cwmp__SetVouchers cwmp__SetVouchers;

	memset(&cwmp__SetVouchers, 0, sizeof(struct _cwmp__SetVouchers));

	soap_serializeheader(soap);
	soap_serialize__cwmp__SetVouchers(soap, &cwmp__SetVouchers);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__cwmp__SetVouchers(soap, &cwmp__SetVouchers, "cwmp:SetVouchers", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__cwmp__SetVouchers(soap, &cwmp__SetVouchers, "cwmp:SetVouchers", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;

	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 cwmp__reply_GetOptions(struct soap *soap)
{
	struct _cwmp__GetOptions cwmp__GetOptions;

	memset(&cwmp__GetOptions, 0, sizeof(struct _cwmp__GetOptions));

	soap_serializeheader(soap);
	soap_serialize__cwmp__GetOptions(soap, &cwmp__GetOptions);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__cwmp__GetOptions(soap, &cwmp__GetOptions, "cwmp:GetOptions", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__cwmp__GetOptions(soap, &cwmp__GetOptions, "cwmp:GetOptions", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;

	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 cwmp__reply_Upload(struct soap *soap)
{
	struct _cwmp__Upload cwmp__Upload;

	memset(&cwmp__Upload, 0, sizeof(struct _cwmp__Upload));

	soap_serializeheader(soap);
	soap_serialize__cwmp__Upload(soap, &cwmp__Upload);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__cwmp__Upload(soap, &cwmp__Upload, "cwmp:Upload", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__cwmp__Upload(soap, &cwmp__Upload, "cwmp:Upload", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;

	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 cwmp__reply_FactoryReset(struct soap *soap)
{
	struct _cwmp__FactoryReset cwmp__FactoryReset;

	memset(&cwmp__FactoryReset, 0, sizeof(struct _cwmp__FactoryReset));

	soap_serializeheader(soap);
	soap_serialize__cwmp__FactoryReset(soap, &cwmp__FactoryReset);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__cwmp__FactoryReset(soap, &cwmp__FactoryReset, "cwmp:FactoryReset", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__cwmp__FactoryReset(soap, &cwmp__FactoryReset, "cwmp:FactoryReset", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;

	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 cwmp__reply_GetAllQueuedTransfers(struct soap *soap)
{
	struct _cwmp__GetAllQueuedTransfers cwmp__GetAllQueuedTransfers;

	memset(&cwmp__GetAllQueuedTransfers, 0, sizeof(struct _cwmp__GetAllQueuedTransfers));

	soap_serializeheader(soap);
	soap_serialize__cwmp__GetAllQueuedTransfers(soap, &cwmp__GetAllQueuedTransfers);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__cwmp__GetAllQueuedTransfers(soap, &cwmp__GetAllQueuedTransfers, "cwmp:GetAllQueuedTransfers", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__cwmp__GetAllQueuedTransfers(soap, &cwmp__GetAllQueuedTransfers, "cwmp:GetAllQueuedTransfers", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;

	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 cwmp__reply_EmptyPost(struct soap *soap)
{
	if(soap_response(soap,204)
		|| soap_end_send(soap))
		return soap->error;
	
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 cwmp__reply_RPCMessage(struct soap *soap)
{
	static int i = 0;
	if(i == 0) 
		cwmp__reply_GetRPCMethods(soap);
	else if(i == 1)
		cwmp__reply_SetParameterValues(soap);
	else if(i == 2)
		cwmp__reply_GetParameterValues(soap);
	else if(i == 3)
		cwmp__reply_GetParameterNames(soap);
	else if(i == 4)
		cwmp__reply_SetParameterAttributes(soap);
	else if(i == 5)
		cwmp__reply_GetParameterAttributes(soap);
	else if(i == 6)
		cwmp__reply_AddObject(soap);
	else if(i == 7)
		cwmp__reply_DeleteObject(soap);
	else if(i == 8)
		cwmp__reply_Download(soap);
	else if(i == 9)
		cwmp__reply_Reboot(soap);
	else if(i == 10)
		cwmp__reply_GetQueuedTransfers(soap);
	else if(i == 11)
		cwmp__reply_ScheduleInform(soap);
	else if(i == 12)
		cwmp__reply_SetVouchers(soap);
	else if(i == 13)
		cwmp__reply_GetOptions(soap);
	else if(i == 14)
		cwmp__reply_Upload(soap);
	else if(i == 15)
		cwmp__reply_EmptyPost(soap); 
	else {
		i = 0;
		cwmp__reply_GetRPCMethods(soap);
	}
	
	i++;

	//soap_destroy(soap);
	soap_closesock(soap);
	
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp__GetRPCMethods(struct soap *soap)
{	struct __cwmp__GetRPCMethods soap_tmp___cwmp__GetRPCMethods;
	soap_default___cwmp__GetRPCMethods(soap, &soap_tmp___cwmp__GetRPCMethods);
	soap->encodingStyle = NULL;
	if (!soap_get___cwmp__GetRPCMethods(soap, &soap_tmp___cwmp__GetRPCMethods, "-cwmp:GetRPCMethods", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __cwmp__GetRPCMethods(soap, soap_tmp___cwmp__GetRPCMethods.cwmp__GetRPCMethodsResponse);
	if (soap->error)
		return soap->error;

	if(SOAP_OK != cwmp__reply_RPCMessage(soap)) {
		fprintf(stderr, "%s:Failed to Reply Message to CPE\n", __func__);
	}
	
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp__SetParameterValues(struct soap *soap)
{	struct __cwmp__SetParameterValues soap_tmp___cwmp__SetParameterValues;
	soap_default___cwmp__SetParameterValues(soap, &soap_tmp___cwmp__SetParameterValues);
	soap->encodingStyle = NULL;
	if (!soap_get___cwmp__SetParameterValues(soap, &soap_tmp___cwmp__SetParameterValues, "-cwmp:SetParameterValues", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __cwmp__SetParameterValues(soap, soap_tmp___cwmp__SetParameterValues.cwmp__SetParameterValuesResponse);
	if (soap->error)
		return soap->error;
	
	if(SOAP_OK != cwmp__reply_RPCMessage(soap)) {
		fprintf(stderr, "%s:Failed to Reply Message to CPE\n", __func__);
	}
	
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp__GetParameterValues(struct soap *soap)
{	struct __cwmp__GetParameterValues soap_tmp___cwmp__GetParameterValues;
	soap_default___cwmp__GetParameterValues(soap, &soap_tmp___cwmp__GetParameterValues);
	soap->encodingStyle = NULL;
	if (!soap_get___cwmp__GetParameterValues(soap, &soap_tmp___cwmp__GetParameterValues, "-cwmp:GetParameterValues", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __cwmp__GetParameterValues(soap, soap_tmp___cwmp__GetParameterValues.cwmp__GetParameterValuesResponse);
	if (soap->error)
		return soap->error;
	
	if(SOAP_OK != cwmp__reply_RPCMessage(soap)) {
		fprintf(stderr, "%s:Failed to Reply Message to CPE\n", __func__);
	}
	
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp__GetParameterNames(struct soap *soap)
{	struct __cwmp__GetParameterNames soap_tmp___cwmp__GetParameterNames;
	soap_default___cwmp__GetParameterNames(soap, &soap_tmp___cwmp__GetParameterNames);
	soap->encodingStyle = NULL;
	if (!soap_get___cwmp__GetParameterNames(soap, &soap_tmp___cwmp__GetParameterNames, "-cwmp:GetParameterNames", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __cwmp__GetParameterNames(soap, soap_tmp___cwmp__GetParameterNames.cwmp__GetParameterNamesResponse);
	if (soap->error)
		return soap->error;
	
	if(SOAP_OK != cwmp__reply_RPCMessage(soap)) {
		fprintf(stderr, "%s:Failed to Reply Message to CPE\n", __func__);
	}
	
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp__SetParameterAttributes(struct soap *soap)
{	struct __cwmp__SetParameterAttributes soap_tmp___cwmp__SetParameterAttributes;
	soap_default___cwmp__SetParameterAttributes(soap, &soap_tmp___cwmp__SetParameterAttributes);
	soap->encodingStyle = NULL;
	if (!soap_get___cwmp__SetParameterAttributes(soap, &soap_tmp___cwmp__SetParameterAttributes, "-cwmp:SetParameterAttributes", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __cwmp__SetParameterAttributes(soap, soap_tmp___cwmp__SetParameterAttributes.cwmp__SetParameterAttributesResponse);
	if (soap->error)
		return soap->error;
	
	if(SOAP_OK != cwmp__reply_RPCMessage(soap)) {
		fprintf(stderr, "%s:Failed to Reply Message to CPE\n", __func__);
	}
	
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp__GetParameterAttributes(struct soap *soap)
{	struct __cwmp__GetParameterAttributes soap_tmp___cwmp__GetParameterAttributes;
	soap_default___cwmp__GetParameterAttributes(soap, &soap_tmp___cwmp__GetParameterAttributes);
	soap->encodingStyle = NULL;
	if (!soap_get___cwmp__GetParameterAttributes(soap, &soap_tmp___cwmp__GetParameterAttributes, "-cwmp:GetParameterAttributes", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __cwmp__GetParameterAttributes(soap, soap_tmp___cwmp__GetParameterAttributes.cwmp__GetParameterAttributesResponse);
	if (soap->error)
		return soap->error;
	
	if(SOAP_OK != cwmp__reply_RPCMessage(soap)) {
		fprintf(stderr, "%s:Failed to Reply Message to CPE\n", __func__);
	}
	
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp__AddObject(struct soap *soap)
{	struct __cwmp__AddObject soap_tmp___cwmp__AddObject;
	soap_default___cwmp__AddObject(soap, &soap_tmp___cwmp__AddObject);
	soap->encodingStyle = NULL;
	if (!soap_get___cwmp__AddObject(soap, &soap_tmp___cwmp__AddObject, "-cwmp:AddObject", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __cwmp__AddObject(soap, soap_tmp___cwmp__AddObject.cwmp__AddObjectResponse);
	if (soap->error)
		return soap->error;
	
	if(SOAP_OK != cwmp__reply_RPCMessage(soap)) {
		fprintf(stderr, "%s:Failed to Reply Message to CPE\n", __func__);
	}
	
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp__DeleteObject(struct soap *soap)
{	struct __cwmp__DeleteObject soap_tmp___cwmp__DeleteObject;
	soap_default___cwmp__DeleteObject(soap, &soap_tmp___cwmp__DeleteObject);
	soap->encodingStyle = NULL;
	if (!soap_get___cwmp__DeleteObject(soap, &soap_tmp___cwmp__DeleteObject, "-cwmp:DeleteObject", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __cwmp__DeleteObject(soap, soap_tmp___cwmp__DeleteObject.cwmp__DeleteObjectResponse);
	if (soap->error)
		return soap->error;
	
	if(SOAP_OK != cwmp__reply_RPCMessage(soap)) {
		fprintf(stderr, "%s:Failed to Reply Message to CPE\n", __func__);
	}
	
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp__Download(struct soap *soap)
{	struct __cwmp__Download soap_tmp___cwmp__Download;
	soap_default___cwmp__Download(soap, &soap_tmp___cwmp__Download);
	soap->encodingStyle = NULL;
	if (!soap_get___cwmp__Download(soap, &soap_tmp___cwmp__Download, "-cwmp:Download", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __cwmp__Download(soap, soap_tmp___cwmp__Download.cwmp__DownloadResponse);
	if (soap->error)
		return soap->error;
	
	if(SOAP_OK != cwmp__reply_RPCMessage(soap)) {
		fprintf(stderr, "%s:Failed to Reply Message to CPE\n", __func__);
	}
	
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp__Reboot(struct soap *soap)
{	struct __cwmp__Reboot soap_tmp___cwmp__Reboot;
	soap_default___cwmp__Reboot(soap, &soap_tmp___cwmp__Reboot);
	soap->encodingStyle = NULL;
	if (!soap_get___cwmp__Reboot(soap, &soap_tmp___cwmp__Reboot, "-cwmp:Reboot", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __cwmp__Reboot(soap, soap_tmp___cwmp__Reboot.cwmp__RebootResponse);
	if (soap->error)
		return soap->error;
	
	if(SOAP_OK != cwmp__reply_RPCMessage(soap)) {
		fprintf(stderr, "%s:Failed to Reply Message to CPE\n", __func__);
	}
	
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp__GetQueuedTransfers(struct soap *soap)
{	struct __cwmp__GetQueuedTransfers soap_tmp___cwmp__GetQueuedTransfers;
	soap_default___cwmp__GetQueuedTransfers(soap, &soap_tmp___cwmp__GetQueuedTransfers);
	soap->encodingStyle = NULL;
	if (!soap_get___cwmp__GetQueuedTransfers(soap, &soap_tmp___cwmp__GetQueuedTransfers, "-cwmp:GetQueuedTransfers", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __cwmp__GetQueuedTransfers(soap, soap_tmp___cwmp__GetQueuedTransfers.cwmp__GetQueuedTransfersResponse);
	if (soap->error)
		return soap->error;
	
	if(SOAP_OK != cwmp__reply_RPCMessage(soap)) {
		fprintf(stderr, "%s:Failed to Reply Message to CPE\n", __func__);
	}
	
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp__ScheduleInform(struct soap *soap)
{	struct __cwmp__ScheduleInform soap_tmp___cwmp__ScheduleInform;
	soap_default___cwmp__ScheduleInform(soap, &soap_tmp___cwmp__ScheduleInform);
	soap->encodingStyle = NULL;
	if (!soap_get___cwmp__ScheduleInform(soap, &soap_tmp___cwmp__ScheduleInform, "-cwmp:ScheduleInform", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __cwmp__ScheduleInform(soap, soap_tmp___cwmp__ScheduleInform.cwmp__ScheduleInformResponse);
	if (soap->error)
		return soap->error;
	
	if(SOAP_OK != cwmp__reply_RPCMessage(soap)) {
		fprintf(stderr, "%s:Failed to Reply Message to CPE\n", __func__);
	}
	
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp__SetVouchers(struct soap *soap)
{	struct __cwmp__SetVouchers soap_tmp___cwmp__SetVouchers;
	soap_default___cwmp__SetVouchers(soap, &soap_tmp___cwmp__SetVouchers);
	soap->encodingStyle = NULL;
	if (!soap_get___cwmp__SetVouchers(soap, &soap_tmp___cwmp__SetVouchers, "-cwmp:SetVouchers", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __cwmp__SetVouchers(soap, soap_tmp___cwmp__SetVouchers.cwmp__SetVouchersResponse);
	if (soap->error)
		return soap->error;
	
	if(SOAP_OK != cwmp__reply_RPCMessage(soap)) {
		fprintf(stderr, "%s:Failed to Reply Message to CPE\n", __func__);
	}
	
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp__GetOptions(struct soap *soap)
{	struct __cwmp__GetOptions soap_tmp___cwmp__GetOptions;
	soap_default___cwmp__GetOptions(soap, &soap_tmp___cwmp__GetOptions);
	soap->encodingStyle = NULL;
	if (!soap_get___cwmp__GetOptions(soap, &soap_tmp___cwmp__GetOptions, "-cwmp:GetOptions", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __cwmp__GetOptions(soap, soap_tmp___cwmp__GetOptions.cwmp__GetOptionsResponse);
	if (soap->error)
		return soap->error;
	
	if(SOAP_OK != cwmp__reply_RPCMessage(soap)) {
		fprintf(stderr, "%s:Failed to Reply Message to CPE\n", __func__);
	}
	
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp__Upload(struct soap *soap)
{	struct __cwmp__Upload soap_tmp___cwmp__Upload;
	soap_default___cwmp__Upload(soap, &soap_tmp___cwmp__Upload);
	soap->encodingStyle = NULL;
	if (!soap_get___cwmp__Upload(soap, &soap_tmp___cwmp__Upload, "-cwmp:Upload", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __cwmp__Upload(soap, soap_tmp___cwmp__Upload.cwmp__UploadResponse);
	if (soap->error)
		return soap->error;
	
	if(SOAP_OK != cwmp__reply_RPCMessage(soap)) {
		fprintf(stderr, "%s:Failed to Reply Message to CPE\n", __func__);
	}
	
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp__FactoryReset(struct soap *soap)
{	struct __cwmp__FactoryReset soap_tmp___cwmp__FactoryReset;
	soap_default___cwmp__FactoryReset(soap, &soap_tmp___cwmp__FactoryReset);
	soap->encodingStyle = NULL;
	if (!soap_get___cwmp__FactoryReset(soap, &soap_tmp___cwmp__FactoryReset, "-cwmp:FactoryReset", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __cwmp__FactoryReset(soap, soap_tmp___cwmp__FactoryReset.cwmp__FactoryResetResponse);
	if (soap->error)
		return soap->error;
	
	if(SOAP_OK != cwmp__reply_RPCMessage(soap)) {
		fprintf(stderr, "%s:Failed to Reply Message to CPE\n", __func__);
	}
	
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp__GetAllQueuedTransfers(struct soap *soap)
{	struct __cwmp__GetAllQueuedTransfers soap_tmp___cwmp__GetAllQueuedTransfers;
	soap_default___cwmp__GetAllQueuedTransfers(soap, &soap_tmp___cwmp__GetAllQueuedTransfers);
	soap->encodingStyle = NULL;
	if (!soap_get___cwmp__GetAllQueuedTransfers(soap, &soap_tmp___cwmp__GetAllQueuedTransfers, "-cwmp:GetAllQueuedTransfers", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __cwmp__GetAllQueuedTransfers(soap, soap_tmp___cwmp__GetAllQueuedTransfers.cwmp__GetAllQueuedTransfersResponse);
	if (soap->error)
		return soap->error;
	
	if(SOAP_OK != cwmp__reply_RPCMessage(soap)) {
		fprintf(stderr, "%s:Failed to Reply Message to CPE\n", __func__);
	}
	
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp__Inform(struct soap *soap)
{	struct __cwmp__Inform soap_tmp___cwmp__Inform;
	struct _cwmp__InformResponse cwmp__InformResponse;
	soap_default__cwmp__InformResponse(soap, &cwmp__InformResponse);
	soap_default___cwmp__Inform(soap, &soap_tmp___cwmp__Inform);
	soap->encodingStyle = NULL;
	if (!soap_get___cwmp__Inform(soap, &soap_tmp___cwmp__Inform, "-cwmp:Inform", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __cwmp__Inform(soap, soap_tmp___cwmp__Inform.cwmp__Inform, &cwmp__InformResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize__cwmp__InformResponse(soap, &cwmp__InformResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__cwmp__InformResponse(soap, &cwmp__InformResponse, "cwmp:InformResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__cwmp__InformResponse(soap, &cwmp__InformResponse, "cwmp:InformResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp__TransferComplete(struct soap *soap)
{	struct __cwmp__TransferComplete soap_tmp___cwmp__TransferComplete;
	struct _cwmp__TransferCompleteResponse cwmp__TransferCompleteResponse;
	soap_default__cwmp__TransferCompleteResponse(soap, &cwmp__TransferCompleteResponse);
	soap_default___cwmp__TransferComplete(soap, &soap_tmp___cwmp__TransferComplete);
	soap->encodingStyle = NULL;
	if (!soap_get___cwmp__TransferComplete(soap, &soap_tmp___cwmp__TransferComplete, "-cwmp:TransferComplete", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __cwmp__TransferComplete(soap, soap_tmp___cwmp__TransferComplete.cwmp__TransferComplete, &cwmp__TransferCompleteResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize__cwmp__TransferCompleteResponse(soap, &cwmp__TransferCompleteResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__cwmp__TransferCompleteResponse(soap, &cwmp__TransferCompleteResponse, "cwmp:TransferCompleteResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__cwmp__TransferCompleteResponse(soap, &cwmp__TransferCompleteResponse, "cwmp:TransferCompleteResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp__AutonomousTransferComplete(struct soap *soap)
{	struct __cwmp__AutonomousTransferComplete soap_tmp___cwmp__AutonomousTransferComplete;
	struct _cwmp__AutonomousTransferCompleteResponse cwmp__AutonomousTransferCompleteResponse;
	soap_default__cwmp__AutonomousTransferCompleteResponse(soap, &cwmp__AutonomousTransferCompleteResponse);
	soap_default___cwmp__AutonomousTransferComplete(soap, &soap_tmp___cwmp__AutonomousTransferComplete);
	soap->encodingStyle = NULL;
	if (!soap_get___cwmp__AutonomousTransferComplete(soap, &soap_tmp___cwmp__AutonomousTransferComplete, "-cwmp:AutonomousTransferComplete", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __cwmp__AutonomousTransferComplete(soap, soap_tmp___cwmp__AutonomousTransferComplete.cwmp__AutonomousTransferComplete, &cwmp__AutonomousTransferCompleteResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize__cwmp__AutonomousTransferCompleteResponse(soap, &cwmp__AutonomousTransferCompleteResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__cwmp__AutonomousTransferCompleteResponse(soap, &cwmp__AutonomousTransferCompleteResponse, "cwmp:AutonomousTransferCompleteResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__cwmp__AutonomousTransferCompleteResponse(soap, &cwmp__AutonomousTransferCompleteResponse, "cwmp:AutonomousTransferCompleteResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp__Kicked(struct soap *soap)
{	struct __cwmp__Kicked soap_tmp___cwmp__Kicked;
	struct _cwmp__KickedResponse cwmp__KickedResponse;
	soap_default__cwmp__KickedResponse(soap, &cwmp__KickedResponse);
	soap_default___cwmp__Kicked(soap, &soap_tmp___cwmp__Kicked);
	soap->encodingStyle = NULL;
	if (!soap_get___cwmp__Kicked(soap, &soap_tmp___cwmp__Kicked, "-cwmp:Kicked", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __cwmp__Kicked(soap, soap_tmp___cwmp__Kicked.cwmp__Kicked, &cwmp__KickedResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize__cwmp__KickedResponse(soap, &cwmp__KickedResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__cwmp__KickedResponse(soap, &cwmp__KickedResponse, "cwmp:KickedResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__cwmp__KickedResponse(soap, &cwmp__KickedResponse, "cwmp:KickedResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp__RequestDownload(struct soap *soap)
{	struct __cwmp__RequestDownload soap_tmp___cwmp__RequestDownload;
	struct _cwmp__RequestDownloadResponse cwmp__RequestDownloadResponse;
	soap_default__cwmp__RequestDownloadResponse(soap, &cwmp__RequestDownloadResponse);
	soap_default___cwmp__RequestDownload(soap, &soap_tmp___cwmp__RequestDownload);
	soap->encodingStyle = NULL;
	if (!soap_get___cwmp__RequestDownload(soap, &soap_tmp___cwmp__RequestDownload, "-cwmp:RequestDownload", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __cwmp__RequestDownload(soap, soap_tmp___cwmp__RequestDownload.cwmp__RequestDownload, &cwmp__RequestDownloadResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize__cwmp__RequestDownloadResponse(soap, &cwmp__RequestDownloadResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__cwmp__RequestDownloadResponse(soap, &cwmp__RequestDownloadResponse, "cwmp:RequestDownloadResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__cwmp__RequestDownloadResponse(soap, &cwmp__RequestDownloadResponse, "cwmp:RequestDownloadResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp__Fault(struct soap *soap)
{	struct __cwmp__Fault soap_tmp___cwmp__Fault;
	soap_default___cwmp__Fault(soap, &soap_tmp___cwmp__Fault);
	soap->encodingStyle = NULL;
	if (!soap_get___cwmp__Fault(soap, &soap_tmp___cwmp__Fault, "-cwmp:Fault", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __cwmp__Fault(soap, soap_tmp___cwmp__Fault.cwmp__Fault);
	if (soap->error)
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp__EmptyPost(struct soap *soap)
{	struct __cwmp__EmptyPost soap_tmp___cwmp__EmptyPost;
	struct _cwmp__KickedResponse cwmp__KickedResponse;
	soap_default__cwmp__KickedResponse(soap, &cwmp__KickedResponse);
	soap_default___cwmp__EmptyPost(soap, &soap_tmp___cwmp__EmptyPost);
	soap->encodingStyle = NULL;
	if (!soap_get___cwmp__EmptyPost(soap, &soap_tmp___cwmp__EmptyPost, "-cwmp:EmptyPost", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __cwmp__EmptyPost(soap, soap_tmp___cwmp__EmptyPost.cwmp__Fault, &cwmp__KickedResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize__cwmp__KickedResponse(soap, &cwmp__KickedResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__cwmp__KickedResponse(soap, &cwmp__KickedResponse, "cwmp:KickedResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__cwmp__KickedResponse(soap, &cwmp__KickedResponse, "cwmp:KickedResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

#ifdef __cplusplus
}
#endif

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapServer.c */
