/* soapStub.h
   Generated by gSOAP 2.8.5 from cwmp-1-1.h

Copyright(C) 2000-2011, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapStub_H
#define soapStub_H
#define SOAP_NAMESPACE_OF_ns1	""
#define SOAP_NAMESPACE_OF_cwmp	"urn:dslforum-org:cwmp-1-1"
#include "stdsoap2.h"
#ifdef __cplusplus
extern "C" {
#endif

/******************************************************************************\
 *                                                                            *
 * Enumerations                                                               *
 *                                                                            *
\******************************************************************************/


#ifndef SOAP_TYPE_xsd__boolean
#define SOAP_TYPE_xsd__boolean (12)
/* xsd:boolean */
enum xsd__boolean {xsd__boolean__false_ = 0, xsd__boolean__true_ = 1};
#endif

#ifndef SOAP_TYPE__cwmp__SetParameterAttributesStruct_Notification
#define SOAP_TYPE__cwmp__SetParameterAttributesStruct_Notification (24)
/* cwmp:SetParameterAttributesStruct-Notification */
enum _cwmp__SetParameterAttributesStruct_Notification {_cwmp__SetParameterAttributesStruct_Notification__0 = 0, _cwmp__SetParameterAttributesStruct_Notification__1 = 1, _cwmp__SetParameterAttributesStruct_Notification__2 = 2};
#endif

#ifndef SOAP_TYPE__cwmp__ParameterAttributeStruct_Notification
#define SOAP_TYPE__cwmp__ParameterAttributeStruct_Notification (28)
/* cwmp:ParameterAttributeStruct-Notification */
enum _cwmp__ParameterAttributeStruct_Notification {_cwmp__ParameterAttributeStruct_Notification__0 = 0, _cwmp__ParameterAttributeStruct_Notification__1 = 1, _cwmp__ParameterAttributeStruct_Notification__2 = 2};
#endif

#ifndef SOAP_TYPE__cwmp__QueuedTransferStruct_State
#define SOAP_TYPE__cwmp__QueuedTransferStruct_State (30)
/* cwmp:QueuedTransferStruct-State */
enum _cwmp__QueuedTransferStruct_State {_cwmp__QueuedTransferStruct_State__1 = 1, _cwmp__QueuedTransferStruct_State__2 = 2, _cwmp__QueuedTransferStruct_State__3 = 3};
#endif

#ifndef SOAP_TYPE__cwmp__AllQueuedTransferStruct_State
#define SOAP_TYPE__cwmp__AllQueuedTransferStruct_State (32)
/* cwmp:AllQueuedTransferStruct-State */
enum _cwmp__AllQueuedTransferStruct_State {_cwmp__AllQueuedTransferStruct_State__1 = 1, _cwmp__AllQueuedTransferStruct_State__2 = 2, _cwmp__AllQueuedTransferStruct_State__3 = 3};
#endif

#ifndef SOAP_TYPE__cwmp__OptionStruct_State
#define SOAP_TYPE__cwmp__OptionStruct_State (34)
/* cwmp:OptionStruct-State */
enum _cwmp__OptionStruct_State {_cwmp__OptionStruct_State__0 = 0, _cwmp__OptionStruct_State__1 = 1, _cwmp__OptionStruct_State__2 = 2, _cwmp__OptionStruct_State__3 = 3};
#endif

#ifndef SOAP_TYPE__cwmp__OptionStruct_Mode
#define SOAP_TYPE__cwmp__OptionStruct_Mode (35)
/* cwmp:OptionStruct-Mode */
enum _cwmp__OptionStruct_Mode {_cwmp__OptionStruct_Mode__0 = 0, _cwmp__OptionStruct_Mode__1 = 1, _cwmp__OptionStruct_Mode__2 = 2};
#endif

#ifndef SOAP_TYPE__cwmp__OptionStruct_IsTransferable
#define SOAP_TYPE__cwmp__OptionStruct_IsTransferable (38)
/* cwmp:OptionStruct-IsTransferable */
enum _cwmp__OptionStruct_IsTransferable {_cwmp__OptionStruct_IsTransferable__0 = 0, _cwmp__OptionStruct_IsTransferable__1 = 1};
#endif

#ifndef SOAP_TYPE__cwmp__SetParameterValuesResponse_Status
#define SOAP_TYPE__cwmp__SetParameterValuesResponse_Status (51)
/* cwmp:SetParameterValuesResponse-Status */
enum _cwmp__SetParameterValuesResponse_Status {_cwmp__SetParameterValuesResponse_Status__0 = 0, _cwmp__SetParameterValuesResponse_Status__1 = 1};
#endif

#ifndef SOAP_TYPE__cwmp__AddObjectResponse_Status
#define SOAP_TYPE__cwmp__AddObjectResponse_Status (70)
/* cwmp:AddObjectResponse-Status */
enum _cwmp__AddObjectResponse_Status {_cwmp__AddObjectResponse_Status__0 = 0, _cwmp__AddObjectResponse_Status__1 = 1};
#endif

#ifndef SOAP_TYPE__cwmp__DeleteObjectResponse_Status
#define SOAP_TYPE__cwmp__DeleteObjectResponse_Status (73)
/* cwmp:DeleteObjectResponse-Status */
enum _cwmp__DeleteObjectResponse_Status {_cwmp__DeleteObjectResponse_Status__0 = 0, _cwmp__DeleteObjectResponse_Status__1 = 1};
#endif

#ifndef SOAP_TYPE__cwmp__DownloadResponse_Status
#define SOAP_TYPE__cwmp__DownloadResponse_Status (76)
/* cwmp:DownloadResponse-Status */
enum _cwmp__DownloadResponse_Status {_cwmp__DownloadResponse_Status__0 = 0, _cwmp__DownloadResponse_Status__1 = 1};
#endif

#ifndef SOAP_TYPE__cwmp__UploadResponse_Status
#define SOAP_TYPE__cwmp__UploadResponse_Status (95)
/* cwmp:UploadResponse-Status */
enum _cwmp__UploadResponse_Status {_cwmp__UploadResponse_Status__0 = 0, _cwmp__UploadResponse_Status__1 = 1};
#endif

/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Classes and Structs                                                        *
 *                                                                            *
\******************************************************************************/


#if 0 /* volatile type: do not declare here, declared elsewhere */

#endif

#ifndef SOAP_TYPE_SOAP_ENC__base64
#define SOAP_TYPE_SOAP_ENC__base64 (7)
/* Base64 schema type: */
struct SOAP_ENC__base64
{
	unsigned char *__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_cwmp__FaultStruct
#define SOAP_TYPE_cwmp__FaultStruct (17)
/* cwmp:FaultStruct */
struct cwmp__FaultStruct
{
	char *FaultCode;	/* required element of type xsd:string */
	char *FaultString;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_cwmp__DeviceIdStruct
#define SOAP_TYPE_cwmp__DeviceIdStruct (18)
/* cwmp:DeviceIdStruct */
struct cwmp__DeviceIdStruct
{
	char *Manufacturer;	/* required element of type xsd:string */
	char *OUI;	/* required element of type xsd:string */
	char *ProductClass;	/* required element of type xsd:string */
	char *SerialNumber;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_cwmp__EventStruct
#define SOAP_TYPE_cwmp__EventStruct (19)
/* cwmp:EventStruct */
struct cwmp__EventStruct
{
	char *EventCode;	/* required element of type xsd:string */
	char *CommandKey;	/* required element of type cwmp:CommandKeyType */
};
#endif

#ifndef SOAP_TYPE_cwmp__ParameterValueStruct
#define SOAP_TYPE_cwmp__ParameterValueStruct (20)
/* cwmp:ParameterValueStruct */
struct cwmp__ParameterValueStruct
{
	char *Name;	/* required element of type xsd:string */
	char *Value;	/* required element of type xsd:anySimpleType */
};
#endif

#ifndef SOAP_TYPE_cwmp__ParameterInfoStruct
#define SOAP_TYPE_cwmp__ParameterInfoStruct (21)
/* cwmp:ParameterInfoStruct */
struct cwmp__ParameterInfoStruct
{
	char *Name;	/* required element of type xsd:string */
	enum xsd__boolean Writable;	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_cwmp__SetParameterAttributesStruct
#define SOAP_TYPE_cwmp__SetParameterAttributesStruct (22)
/* cwmp:SetParameterAttributesStruct */
struct cwmp__SetParameterAttributesStruct
{
	char **Name;	/* optional element of type xsd:string */
	enum xsd__boolean NotificationChange;	/* required element of type xsd:boolean */
	enum _cwmp__SetParameterAttributesStruct_Notification Notification;	/* required element of type cwmp:SetParameterAttributesStruct-Notification */
	enum xsd__boolean AccessListChange;	/* required element of type xsd:boolean */
	struct AccessList *AccessList;	/* required element of type ArrayOfstring */
};
#endif

#ifndef SOAP_TYPE_cwmp__ParameterAttributeStruct
#define SOAP_TYPE_cwmp__ParameterAttributeStruct (27)
/* cwmp:ParameterAttributeStruct */
struct cwmp__ParameterAttributeStruct
{
	char *Name;	/* required element of type xsd:string */
	enum _cwmp__ParameterAttributeStruct_Notification Notification;	/* required element of type cwmp:ParameterAttributeStruct-Notification */
	struct AccessList *AccessList;	/* required element of type ArrayOfstring */
};
#endif

#ifndef SOAP_TYPE_cwmp__QueuedTransferStruct
#define SOAP_TYPE_cwmp__QueuedTransferStruct (29)
/* cwmp:QueuedTransferStruct */
struct cwmp__QueuedTransferStruct
{
	char *CommandKey;	/* required element of type cwmp:CommandKeyType */
	enum _cwmp__QueuedTransferStruct_State State;	/* required element of type cwmp:QueuedTransferStruct-State */
};
#endif

#ifndef SOAP_TYPE_cwmp__AllQueuedTransferStruct
#define SOAP_TYPE_cwmp__AllQueuedTransferStruct (31)
/* cwmp:AllQueuedTransferStruct */
struct cwmp__AllQueuedTransferStruct
{
	char *CommandKey;	/* required element of type cwmp:CommandKeyType */
	enum _cwmp__AllQueuedTransferStruct_State State;	/* required element of type cwmp:AllQueuedTransferStruct-State */
	enum xsd__boolean IsDownload;	/* required element of type xsd:boolean */
	char *FileType;	/* required element of type xsd:string */
	unsigned int FileSize;	/* required element of type xsd:unsignedInt */
	char *TargetFileName;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_cwmp__OptionStruct
#define SOAP_TYPE_cwmp__OptionStruct (33)
/* cwmp:OptionStruct */
struct cwmp__OptionStruct
{
	char *OptionName;	/* required element of type xsd:string */
	unsigned int VoucherSN;	/* required element of type xsd:unsignedInt */
	enum _cwmp__OptionStruct_State State;	/* required element of type cwmp:OptionStruct-State */
	enum _cwmp__OptionStruct_Mode Mode;	/* required element of type cwmp:OptionStruct-Mode */
	time_t StartDate;	/* required element of type xsd:dateTime */
	time_t *ExpirationDate;	/* optional element of type xsd:dateTime */
	enum _cwmp__OptionStruct_IsTransferable IsTransferable;	/* required element of type cwmp:OptionStruct-IsTransferable */
};
#endif

#ifndef SOAP_TYPE_cwmp__ArgStruct
#define SOAP_TYPE_cwmp__ArgStruct (39)
/* cwmp:ArgStruct */
struct cwmp__ArgStruct
{
	char *Name;	/* required element of type xsd:string */
	char *Value;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__cwmp__Fault_SetParameterValuesFault
#define SOAP_TYPE__cwmp__Fault_SetParameterValuesFault (41)
/* cwmp:Fault-SetParameterValuesFault */
struct _cwmp__Fault_SetParameterValuesFault
{
	char *ParameterName;	/* required element of type xsd:string */
	char *FaultCode;	/* required element of type cwmp:FaultCodeType */
	char *FaultString;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__cwmp__Fault
#define SOAP_TYPE__cwmp__Fault (40)
/* cwmp:Fault */
struct _cwmp__Fault
{
	char *FaultCode;	/* required element of type cwmp:FaultCodeType */
	char *FaultString;	/* optional element of type xsd:string */
	int __sizeSetParameterValuesFault;	/* sequence of elements <SetParameterValuesFault> */
	struct _cwmp__Fault_SetParameterValuesFault *SetParameterValuesFault;	/* optional element of type cwmp:Fault-SetParameterValuesFault */
};
#endif

#ifndef SOAP_TYPE__cwmp__GetRPCMethods
#define SOAP_TYPE__cwmp__GetRPCMethods (43)
/* cwmp:GetRPCMethods */
struct _cwmp__GetRPCMethods
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__cwmp__GetRPCMethodsResponse
#define SOAP_TYPE__cwmp__GetRPCMethodsResponse (44)
/* cwmp:GetRPCMethodsResponse */
struct _cwmp__GetRPCMethodsResponse
{
	struct MethodList *MethodList;	/* required element of type ArrayOfstring */
};
#endif

#ifndef SOAP_TYPE__cwmp__SetParameterValues
#define SOAP_TYPE__cwmp__SetParameterValues (47)
/* cwmp:SetParameterValues */
struct _cwmp__SetParameterValues
{
	struct ParameterValueList *ParameterList;	/* required element of type ArrayOfParameterValueStruct */
	char *ParameterKey;	/* required element of type cwmp:ParameterKeyType */
};
#endif

#ifndef SOAP_TYPE__cwmp__SetParameterValuesResponse
#define SOAP_TYPE__cwmp__SetParameterValuesResponse (50)
/* cwmp:SetParameterValuesResponse */
struct _cwmp__SetParameterValuesResponse
{
	enum _cwmp__SetParameterValuesResponse_Status Status;	/* required element of type cwmp:SetParameterValuesResponse-Status */
};
#endif

#ifndef SOAP_TYPE__cwmp__GetParameterValues
#define SOAP_TYPE__cwmp__GetParameterValues (52)
/* cwmp:GetParameterValues */
struct _cwmp__GetParameterValues
{
	struct ParameterNames *ParameterNames;	/* required element of type ArrayOfstring */
};
#endif

#ifndef SOAP_TYPE__cwmp__GetParameterValuesResponse
#define SOAP_TYPE__cwmp__GetParameterValuesResponse (55)
/* cwmp:GetParameterValuesResponse */
struct _cwmp__GetParameterValuesResponse
{
	struct ParameterValueList *ParameterList;	/* required element of type ArrayOfParameterValueStruct */
};
#endif

#ifndef SOAP_TYPE__cwmp__GetParameterNames
#define SOAP_TYPE__cwmp__GetParameterNames (56)
/* cwmp:GetParameterNames */
struct _cwmp__GetParameterNames
{
	char **ParameterPath;	/* optional element of type xsd:string */
	enum xsd__boolean NextLevel;	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE__cwmp__GetParameterNamesResponse
#define SOAP_TYPE__cwmp__GetParameterNamesResponse (57)
/* cwmp:GetParameterNamesResponse */
struct _cwmp__GetParameterNamesResponse
{
	struct ParameterInfoList *ParameterList;	/* required element of type ArrayOfParameterInfoStruct */
};
#endif

#ifndef SOAP_TYPE__cwmp__SetParameterAttributes
#define SOAP_TYPE__cwmp__SetParameterAttributes (60)
/* cwmp:SetParameterAttributes */
struct _cwmp__SetParameterAttributes
{
	struct SetParameterAttributesList *ParameterList;	/* required element of type ArrayOfSetParameterAttributesStruct */
};
#endif

#ifndef SOAP_TYPE__cwmp__SetParameterAttributesResponse
#define SOAP_TYPE__cwmp__SetParameterAttributesResponse (63)
/* cwmp:SetParameterAttributesResponse */
struct _cwmp__SetParameterAttributesResponse
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__cwmp__GetParameterAttributes
#define SOAP_TYPE__cwmp__GetParameterAttributes (64)
/* cwmp:GetParameterAttributes */
struct _cwmp__GetParameterAttributes
{
	struct ParameterNames *ParameterNames;	/* required element of type ArrayOfstring */
};
#endif

#ifndef SOAP_TYPE__cwmp__GetParameterAttributesResponse
#define SOAP_TYPE__cwmp__GetParameterAttributesResponse (65)
/* cwmp:GetParameterAttributesResponse */
struct _cwmp__GetParameterAttributesResponse
{
	struct ParameterAttributeList *ParameterList;	/* required element of type ArrayOfParameterAttributeStruct */
};
#endif

#ifndef SOAP_TYPE__cwmp__AddObject
#define SOAP_TYPE__cwmp__AddObject (68)
/* cwmp:AddObject */
struct _cwmp__AddObject
{
	char *ObjectName;	/* required element of type cwmp:ObjectNameType */
	char *ParameterKey;	/* required element of type cwmp:ParameterKeyType */
};
#endif

#ifndef SOAP_TYPE__cwmp__AddObjectResponse
#define SOAP_TYPE__cwmp__AddObjectResponse (69)
/* cwmp:AddObjectResponse */
struct _cwmp__AddObjectResponse
{
	unsigned int InstanceNumber;	/* required element of type xsd:unsignedInt */
	enum _cwmp__AddObjectResponse_Status Status;	/* required element of type cwmp:AddObjectResponse-Status */
};
#endif

#ifndef SOAP_TYPE__cwmp__DeleteObject
#define SOAP_TYPE__cwmp__DeleteObject (71)
/* cwmp:DeleteObject */
struct _cwmp__DeleteObject
{
	char *ObjectName;	/* required element of type cwmp:ObjectNameType */
	char *ParameterKey;	/* required element of type cwmp:ParameterKeyType */
};
#endif

#ifndef SOAP_TYPE__cwmp__DeleteObjectResponse
#define SOAP_TYPE__cwmp__DeleteObjectResponse (72)
/* cwmp:DeleteObjectResponse */
struct _cwmp__DeleteObjectResponse
{
	enum _cwmp__DeleteObjectResponse_Status Status;	/* required element of type cwmp:DeleteObjectResponse-Status */
};
#endif

#ifndef SOAP_TYPE__cwmp__Download
#define SOAP_TYPE__cwmp__Download (74)
/* cwmp:Download */
struct _cwmp__Download
{
	char *CommandKey;	/* required element of type cwmp:CommandKeyType */
	char *FileType;	/* required element of type xsd:string */
	char *URL;	/* required element of type xsd:string */
	char *Username;	/* required element of type xsd:string */
	char *Password;	/* required element of type xsd:string */
	unsigned int FileSize;	/* required element of type xsd:unsignedInt */
	char *TargetFileName;	/* required element of type xsd:string */
	unsigned int DelaySeconds;	/* required element of type xsd:unsignedInt */
	char *SuccessURL;	/* required element of type xsd:string */
	char *FailureURL;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__cwmp__DownloadResponse
#define SOAP_TYPE__cwmp__DownloadResponse (75)
/* cwmp:DownloadResponse */
struct _cwmp__DownloadResponse
{
	enum _cwmp__DownloadResponse_Status Status;	/* required element of type cwmp:DownloadResponse-Status */
	time_t StartTime;	/* required element of type xsd:dateTime */
	time_t CompleteTime;	/* required element of type xsd:dateTime */
};
#endif

#ifndef SOAP_TYPE__cwmp__Reboot
#define SOAP_TYPE__cwmp__Reboot (77)
/* cwmp:Reboot */
struct _cwmp__Reboot
{
	char *CommandKey;	/* required element of type cwmp:CommandKeyType */
};
#endif

#ifndef SOAP_TYPE__cwmp__RebootResponse
#define SOAP_TYPE__cwmp__RebootResponse (78)
/* cwmp:RebootResponse */
struct _cwmp__RebootResponse
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__cwmp__GetQueuedTransfers
#define SOAP_TYPE__cwmp__GetQueuedTransfers (79)
/* cwmp:GetQueuedTransfers */
struct _cwmp__GetQueuedTransfers
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__cwmp__GetQueuedTransfersResponse
#define SOAP_TYPE__cwmp__GetQueuedTransfersResponse (80)
/* cwmp:GetQueuedTransfersResponse */
struct _cwmp__GetQueuedTransfersResponse
{
	struct TransferList *TransferList;	/* required element of type ArrayOfQueuedTransferStruct */
};
#endif

#ifndef SOAP_TYPE__cwmp__ScheduleInform
#define SOAP_TYPE__cwmp__ScheduleInform (83)
/* cwmp:ScheduleInform */
struct _cwmp__ScheduleInform
{
	unsigned int DelaySeconds;	/* required element of type xsd:unsignedInt */
	char *CommandKey;	/* required element of type cwmp:CommandKeyType */
};
#endif

#ifndef SOAP_TYPE__cwmp__ScheduleInformResponse
#define SOAP_TYPE__cwmp__ScheduleInformResponse (84)
/* cwmp:ScheduleInformResponse */
struct _cwmp__ScheduleInformResponse
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__cwmp__SetVouchers
#define SOAP_TYPE__cwmp__SetVouchers (85)
/* cwmp:SetVouchers */
struct _cwmp__SetVouchers
{
	struct VoucherList *VoucherList;	/* required element of type ArrayOfbase64 */
};
#endif

#ifndef SOAP_TYPE__cwmp__SetVouchersResponse
#define SOAP_TYPE__cwmp__SetVouchersResponse (88)
/* cwmp:SetVouchersResponse */
struct _cwmp__SetVouchersResponse
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__cwmp__GetOptions
#define SOAP_TYPE__cwmp__GetOptions (89)
/* cwmp:GetOptions */
struct _cwmp__GetOptions
{
	char *OptionName;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__cwmp__GetOptionsResponse
#define SOAP_TYPE__cwmp__GetOptionsResponse (90)
/* cwmp:GetOptionsResponse */
struct _cwmp__GetOptionsResponse
{
	struct OptionList *OptionList;	/* required element of type ArrayOfOptionStruct */
};
#endif

#ifndef SOAP_TYPE__cwmp__Upload
#define SOAP_TYPE__cwmp__Upload (93)
/* cwmp:Upload */
struct _cwmp__Upload
{
	char *CommandKey;	/* required element of type cwmp:CommandKeyType */
	char *FileType;	/* required element of type xsd:string */
	char *URL;	/* required element of type xsd:string */
	char *Username;	/* required element of type xsd:string */
	char *Password;	/* required element of type xsd:string */
	unsigned int DelaySeconds;	/* required element of type xsd:unsignedInt */
};
#endif

#ifndef SOAP_TYPE__cwmp__UploadResponse
#define SOAP_TYPE__cwmp__UploadResponse (94)
/* cwmp:UploadResponse */
struct _cwmp__UploadResponse
{
	enum _cwmp__UploadResponse_Status Status;	/* required element of type cwmp:UploadResponse-Status */
	time_t StartTime;	/* required element of type xsd:dateTime */
	time_t CompleteTime;	/* required element of type xsd:dateTime */
};
#endif

#ifndef SOAP_TYPE__cwmp__FactoryReset
#define SOAP_TYPE__cwmp__FactoryReset (96)
/* cwmp:FactoryReset */
struct _cwmp__FactoryReset
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__cwmp__FactoryResetResponse
#define SOAP_TYPE__cwmp__FactoryResetResponse (97)
/* cwmp:FactoryResetResponse */
struct _cwmp__FactoryResetResponse
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__cwmp__GetAllQueuedTransfers
#define SOAP_TYPE__cwmp__GetAllQueuedTransfers (98)
/* cwmp:GetAllQueuedTransfers */
struct _cwmp__GetAllQueuedTransfers
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__cwmp__GetAllQueuedTransfersResponse
#define SOAP_TYPE__cwmp__GetAllQueuedTransfersResponse (99)
/* cwmp:GetAllQueuedTransfersResponse */
struct _cwmp__GetAllQueuedTransfersResponse
{
	struct AllTransferList *TransferList;	/* required element of type ArrayOfAllQueuedTransferStruct */
};
#endif

#ifndef SOAP_TYPE__cwmp__Inform
#define SOAP_TYPE__cwmp__Inform (102)
/* cwmp:Inform */
struct _cwmp__Inform
{
	struct cwmp__DeviceIdStruct *DeviceId;	/* required element of type cwmp:DeviceIdStruct */
	struct EventList *Event;	/* required element of type ArrayOfEventStruct */
	unsigned int MaxEnvelopes;	/* required element of type xsd:unsignedInt */
	time_t CurrentTime;	/* required element of type xsd:dateTime */
	unsigned int RetryCount;	/* required element of type xsd:unsignedInt */
	struct ParameterValueList *ParameterList;	/* required element of type ArrayOfParameterValueStruct */
};
#endif

#ifndef SOAP_TYPE__cwmp__InformResponse
#define SOAP_TYPE__cwmp__InformResponse (106)
/* cwmp:InformResponse */
struct _cwmp__InformResponse
{
	unsigned int MaxEnvelopes;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:unsignedInt */
};
#endif

#ifndef SOAP_TYPE__cwmp__TransferComplete
#define SOAP_TYPE__cwmp__TransferComplete (107)
/* cwmp:TransferComplete */
struct _cwmp__TransferComplete
{
	char *CommandKey;	/* required element of type cwmp:CommandKeyType */
	struct cwmp__FaultStruct *FaultStruct;	/* required element of type cwmp:FaultStruct */
	time_t StartTime;	/* required element of type xsd:dateTime */
	time_t CompleteTime;	/* required element of type xsd:dateTime */
};
#endif

#ifndef SOAP_TYPE__cwmp__TransferCompleteResponse
#define SOAP_TYPE__cwmp__TransferCompleteResponse (109)
/* cwmp:TransferCompleteResponse */
struct _cwmp__TransferCompleteResponse
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__cwmp__AutonomousTransferComplete
#define SOAP_TYPE__cwmp__AutonomousTransferComplete (110)
/* cwmp:AutonomousTransferComplete */
struct _cwmp__AutonomousTransferComplete
{
	char *AnnounceURL;	/* required element of type xsd:string */
	char *TransferURL;	/* required element of type xsd:string */
	enum xsd__boolean IsDownload;	/* required element of type xsd:boolean */
	char *FileType;	/* required element of type xsd:string */
	unsigned int FileSize;	/* required element of type xsd:unsignedInt */
	char *TargetFileName;	/* required element of type xsd:string */
	struct cwmp__FaultStruct *FaultStruct;	/* required element of type cwmp:FaultStruct */
	time_t StartTime;	/* required element of type xsd:dateTime */
	time_t CompleteTime;	/* required element of type xsd:dateTime */
};
#endif

#ifndef SOAP_TYPE__cwmp__AutonomousTransferCompleteResponse
#define SOAP_TYPE__cwmp__AutonomousTransferCompleteResponse (111)
/* cwmp:AutonomousTransferCompleteResponse */
struct _cwmp__AutonomousTransferCompleteResponse
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__cwmp__Kicked
#define SOAP_TYPE__cwmp__Kicked (112)
/* cwmp:Kicked */
struct _cwmp__Kicked
{
	char *Command;	/* required element of type xsd:string */
	char *Referer;	/* required element of type xsd:string */
	char *Arg;	/* required element of type xsd:string */
	char *Next;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__cwmp__KickedResponse
#define SOAP_TYPE__cwmp__KickedResponse (113)
/* cwmp:KickedResponse */
struct _cwmp__KickedResponse
{
	char *NextURL;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__cwmp__RequestDownload
#define SOAP_TYPE__cwmp__RequestDownload (114)
/* cwmp:RequestDownload */
struct _cwmp__RequestDownload
{
	char *FileType;	/* required element of type xsd:string */
	struct FileTypeArg *FileTypeArg;	/* required element of type ArrayOfArgStruct */
};
#endif

#ifndef SOAP_TYPE__cwmp__RequestDownloadResponse
#define SOAP_TYPE__cwmp__RequestDownloadResponse (117)
/* cwmp:RequestDownloadResponse */
struct _cwmp__RequestDownloadResponse
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE_MethodList
#define SOAP_TYPE_MethodList (45)
/* SOAP encoded array of xsd:string schema type: */
struct MethodList
{
	char **__ptrstring;
	int __size;
};
#endif

#ifndef SOAP_TYPE_EventList
#define SOAP_TYPE_EventList (104)
/* SOAP encoded array of cwmp:EventStruct schema type: */
struct EventList
{
	struct cwmp__EventStruct **__ptrEventStruct;
	int __size;
};
#endif

#ifndef SOAP_TYPE_ParameterValueList
#define SOAP_TYPE_ParameterValueList (48)
/* SOAP encoded array of cwmp:ParameterValueStruct schema type: */
struct ParameterValueList
{
	struct cwmp__ParameterValueStruct **__ptrParameterValueStruct;
	int __size;
};
#endif

#ifndef SOAP_TYPE_ParameterInfoList
#define SOAP_TYPE_ParameterInfoList (58)
/* SOAP encoded array of cwmp:ParameterInfoStruct schema type: */
struct ParameterInfoList
{
	struct cwmp__ParameterInfoStruct **__ptrParameterInfoStruct;
	int __size;
};
#endif

#ifndef SOAP_TYPE_ParameterNames
#define SOAP_TYPE_ParameterNames (53)
/* SOAP encoded array of xsd:string schema type: */
struct ParameterNames
{
	char **__ptrstring;
	int __size;
};
#endif

#ifndef SOAP_TYPE_AccessList
#define SOAP_TYPE_AccessList (25)
/* SOAP encoded array of xsd:string schema type: */
struct AccessList
{
	char **__ptrstring;
	int __size;
};
#endif

#ifndef SOAP_TYPE_SetParameterAttributesList
#define SOAP_TYPE_SetParameterAttributesList (61)
/* SOAP encoded array of cwmp:SetParameterAttributesStruct schema type: */
struct SetParameterAttributesList
{
	struct cwmp__SetParameterAttributesStruct **__ptrSetParameterAttributesStruct;
	int __size;
};
#endif

#ifndef SOAP_TYPE_ParameterAttributeList
#define SOAP_TYPE_ParameterAttributeList (66)
/* SOAP encoded array of cwmp:ParameterAttributeStruct schema type: */
struct ParameterAttributeList
{
	struct cwmp__ParameterAttributeStruct **__ptrParameterAttributeStruct;
	int __size;
};
#endif

#ifndef SOAP_TYPE_TransferList
#define SOAP_TYPE_TransferList (81)
/* SOAP encoded array of cwmp:QueuedTransferStruct schema type: */
struct TransferList
{
	struct cwmp__QueuedTransferStruct **__ptrQueuedTransferStruct;
	int __size;
};
#endif

#ifndef SOAP_TYPE_AllTransferList
#define SOAP_TYPE_AllTransferList (100)
/* SOAP encoded array of cwmp:AllQueuedTransferStruct schema type: */
struct AllTransferList
{
	struct cwmp__AllQueuedTransferStruct **__ptrAllQueuedTransferStruct;
	int __size;
};
#endif

#ifndef SOAP_TYPE_VoucherList
#define SOAP_TYPE_VoucherList (86)
/* SOAP encoded array of SOAP-ENC:base64 schema type: */
struct VoucherList
{
	struct SOAP_ENC__base64 **__ptrbase64;
	int __size;
};
#endif

#ifndef SOAP_TYPE_OptionList
#define SOAP_TYPE_OptionList (91)
/* SOAP encoded array of cwmp:OptionStruct schema type: */
struct OptionList
{
	struct cwmp__OptionStruct **__ptrOptionStruct;
	int __size;
};
#endif

#ifndef SOAP_TYPE_FileTypeArg
#define SOAP_TYPE_FileTypeArg (115)
/* SOAP encoded array of cwmp:ArgStruct schema type: */
struct FileTypeArg
{
	struct cwmp__ArgStruct **__ptrArgStruct;
	int __size;
};
#endif

#ifndef SOAP_TYPE__cwmp__ID
#define SOAP_TYPE__cwmp__ID (138)
/* Primitive cwmp:ID schema type: */
struct _cwmp__ID
{
	char *__item;
	char *SOAP_ENV__mustUnderstand;	/* required attribute of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__cwmp__HoldRequests
#define SOAP_TYPE__cwmp__HoldRequests (139)
/* Primitive cwmp:HoldRequests schema type: */
struct _cwmp__HoldRequests
{
	enum xsd__boolean __item;
	char *SOAP_ENV__mustUnderstand;	/* required attribute of type xsd:string */
};
#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (140)
/* SOAP Header: */
struct SOAP_ENV__Header
{
	struct _cwmp__HoldRequests *cwmp__HoldRequests;	/* mustUnderstand */
	struct _cwmp__ID *cwmp__ID;	/* mustUnderstand */
};
#endif

#endif

#ifndef SOAP_TYPE___cwmp__GetRPCMethods
#define SOAP_TYPE___cwmp__GetRPCMethods (146)
/* Operation wrapper: */
struct __cwmp__GetRPCMethods
{
	struct _cwmp__GetRPCMethodsResponse *cwmp__GetRPCMethodsResponse;	/* optional element of type cwmp:GetRPCMethodsResponse */
};
#endif

#ifndef SOAP_TYPE___cwmp__SetParameterValues
#define SOAP_TYPE___cwmp__SetParameterValues (149)
/* Operation wrapper: */
struct __cwmp__SetParameterValues
{
	struct _cwmp__SetParameterValuesResponse *cwmp__SetParameterValuesResponse;	/* optional element of type cwmp:SetParameterValuesResponse */
};
#endif

#ifndef SOAP_TYPE___cwmp__GetParameterValues
#define SOAP_TYPE___cwmp__GetParameterValues (152)
/* Operation wrapper: */
struct __cwmp__GetParameterValues
{
	struct _cwmp__GetParameterValuesResponse *cwmp__GetParameterValuesResponse;	/* optional element of type cwmp:GetParameterValuesResponse */
};
#endif

#ifndef SOAP_TYPE___cwmp__GetParameterNames
#define SOAP_TYPE___cwmp__GetParameterNames (155)
/* Operation wrapper: */
struct __cwmp__GetParameterNames
{
	struct _cwmp__GetParameterNamesResponse *cwmp__GetParameterNamesResponse;	/* optional element of type cwmp:GetParameterNamesResponse */
};
#endif

#ifndef SOAP_TYPE___cwmp__SetParameterAttributes
#define SOAP_TYPE___cwmp__SetParameterAttributes (158)
/* Operation wrapper: */
struct __cwmp__SetParameterAttributes
{
	struct _cwmp__SetParameterAttributesResponse *cwmp__SetParameterAttributesResponse;	/* optional element of type cwmp:SetParameterAttributesResponse */
};
#endif

#ifndef SOAP_TYPE___cwmp__GetParameterAttributes
#define SOAP_TYPE___cwmp__GetParameterAttributes (161)
/* Operation wrapper: */
struct __cwmp__GetParameterAttributes
{
	struct _cwmp__GetParameterAttributesResponse *cwmp__GetParameterAttributesResponse;	/* optional element of type cwmp:GetParameterAttributesResponse */
};
#endif

#ifndef SOAP_TYPE___cwmp__AddObject
#define SOAP_TYPE___cwmp__AddObject (164)
/* Operation wrapper: */
struct __cwmp__AddObject
{
	struct _cwmp__AddObjectResponse *cwmp__AddObjectResponse;	/* optional element of type cwmp:AddObjectResponse */
};
#endif

#ifndef SOAP_TYPE___cwmp__DeleteObject
#define SOAP_TYPE___cwmp__DeleteObject (167)
/* Operation wrapper: */
struct __cwmp__DeleteObject
{
	struct _cwmp__DeleteObjectResponse *cwmp__DeleteObjectResponse;	/* optional element of type cwmp:DeleteObjectResponse */
};
#endif

#ifndef SOAP_TYPE___cwmp__Download
#define SOAP_TYPE___cwmp__Download (170)
/* Operation wrapper: */
struct __cwmp__Download
{
	struct _cwmp__DownloadResponse *cwmp__DownloadResponse;	/* optional element of type cwmp:DownloadResponse */
};
#endif

#ifndef SOAP_TYPE___cwmp__Reboot
#define SOAP_TYPE___cwmp__Reboot (173)
/* Operation wrapper: */
struct __cwmp__Reboot
{
	struct _cwmp__RebootResponse *cwmp__RebootResponse;	/* optional element of type cwmp:RebootResponse */
};
#endif

#ifndef SOAP_TYPE___cwmp__GetQueuedTransfers
#define SOAP_TYPE___cwmp__GetQueuedTransfers (176)
/* Operation wrapper: */
struct __cwmp__GetQueuedTransfers
{
	struct _cwmp__GetQueuedTransfersResponse *cwmp__GetQueuedTransfersResponse;	/* optional element of type cwmp:GetQueuedTransfersResponse */
};
#endif

#ifndef SOAP_TYPE___cwmp__ScheduleInform
#define SOAP_TYPE___cwmp__ScheduleInform (179)
/* Operation wrapper: */
struct __cwmp__ScheduleInform
{
	struct _cwmp__ScheduleInformResponse *cwmp__ScheduleInformResponse;	/* optional element of type cwmp:ScheduleInformResponse */
};
#endif

#ifndef SOAP_TYPE___cwmp__SetVouchers
#define SOAP_TYPE___cwmp__SetVouchers (182)
/* Operation wrapper: */
struct __cwmp__SetVouchers
{
	struct _cwmp__SetVouchersResponse *cwmp__SetVouchersResponse;	/* optional element of type cwmp:SetVouchersResponse */
};
#endif

#ifndef SOAP_TYPE___cwmp__GetOptions
#define SOAP_TYPE___cwmp__GetOptions (185)
/* Operation wrapper: */
struct __cwmp__GetOptions
{
	struct _cwmp__GetOptionsResponse *cwmp__GetOptionsResponse;	/* optional element of type cwmp:GetOptionsResponse */
};
#endif

#ifndef SOAP_TYPE___cwmp__Upload
#define SOAP_TYPE___cwmp__Upload (188)
/* Operation wrapper: */
struct __cwmp__Upload
{
	struct _cwmp__UploadResponse *cwmp__UploadResponse;	/* optional element of type cwmp:UploadResponse */
};
#endif

#ifndef SOAP_TYPE___cwmp__FactoryReset
#define SOAP_TYPE___cwmp__FactoryReset (191)
/* Operation wrapper: */
struct __cwmp__FactoryReset
{
	struct _cwmp__FactoryResetResponse *cwmp__FactoryResetResponse;	/* optional element of type cwmp:FactoryResetResponse */
};
#endif

#ifndef SOAP_TYPE___cwmp__GetAllQueuedTransfers
#define SOAP_TYPE___cwmp__GetAllQueuedTransfers (194)
/* Operation wrapper: */
struct __cwmp__GetAllQueuedTransfers
{
	struct _cwmp__GetAllQueuedTransfersResponse *cwmp__GetAllQueuedTransfersResponse;	/* optional element of type cwmp:GetAllQueuedTransfersResponse */
};
#endif

#ifndef SOAP_TYPE___cwmp__Inform
#define SOAP_TYPE___cwmp__Inform (198)
/* Operation wrapper: */
struct __cwmp__Inform
{
	struct _cwmp__Inform *cwmp__Inform;	/* optional element of type cwmp:Inform */
};
#endif

#ifndef SOAP_TYPE___cwmp__TransferComplete
#define SOAP_TYPE___cwmp__TransferComplete (202)
/* Operation wrapper: */
struct __cwmp__TransferComplete
{
	struct _cwmp__TransferComplete *cwmp__TransferComplete;	/* optional element of type cwmp:TransferComplete */
};
#endif

#ifndef SOAP_TYPE___cwmp__AutonomousTransferComplete
#define SOAP_TYPE___cwmp__AutonomousTransferComplete (206)
/* Operation wrapper: */
struct __cwmp__AutonomousTransferComplete
{
	struct _cwmp__AutonomousTransferComplete *cwmp__AutonomousTransferComplete;	/* optional element of type cwmp:AutonomousTransferComplete */
};
#endif

#ifndef SOAP_TYPE___cwmp__Kicked
#define SOAP_TYPE___cwmp__Kicked (210)
/* Operation wrapper: */
struct __cwmp__Kicked
{
	struct _cwmp__Kicked *cwmp__Kicked;	/* optional element of type cwmp:Kicked */
};
#endif

#ifndef SOAP_TYPE___cwmp__RequestDownload
#define SOAP_TYPE___cwmp__RequestDownload (214)
/* Operation wrapper: */
struct __cwmp__RequestDownload
{
	struct _cwmp__RequestDownload *cwmp__RequestDownload;	/* optional element of type cwmp:RequestDownload */
};
#endif

#ifndef SOAP_TYPE___cwmp__Fault
#define SOAP_TYPE___cwmp__Fault (217)
/* Operation wrapper: */
struct __cwmp__Fault
{
	struct _cwmp__Fault *cwmp__Fault;	/* optional element of type cwmp:Fault */
};
#endif

#ifndef SOAP_TYPE___cwmp__EmptyPost
#define SOAP_TYPE___cwmp__EmptyPost (219)
/* Operation wrapper: */
struct __cwmp__EmptyPost
{
	struct _cwmp__Fault *cwmp__Fault;	/* optional element of type cwmp:Fault */
};
#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (220)
/* SOAP Fault Code: */
struct SOAP_ENV__Code
{
	char *SOAP_ENV__Value;	/* optional element of type xsd:QName */
	struct SOAP_ENV__Code *SOAP_ENV__Subcode;	/* optional element of type SOAP-ENV:Code */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (222)
/* SOAP-ENV:Detail */
struct SOAP_ENV__Detail
{
	char *__any;
	int __type;	/* any type of element <fault> (defined below) */
	void *fault;	/* transient */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (224)
/* SOAP-ENV:Reason */
struct SOAP_ENV__Reason
{
	char *SOAP_ENV__Text;	/* optional element of type xsd:string */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (225)
/* SOAP Fault: */
struct SOAP_ENV__Fault
{
	char *faultcode;	/* optional element of type xsd:QName */
	char *faultstring;	/* optional element of type xsd:string */
	char *faultactor;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *detail;	/* optional element of type SOAP-ENV:Detail */
	struct SOAP_ENV__Code *SOAP_ENV__Code;	/* optional element of type SOAP-ENV:Code */
	struct SOAP_ENV__Reason *SOAP_ENV__Reason;	/* optional element of type SOAP-ENV:Reason */
	char *SOAP_ENV__Node;	/* optional element of type xsd:string */
	char *SOAP_ENV__Role;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *SOAP_ENV__Detail;	/* optional element of type SOAP-ENV:Detail */
};
#endif

#endif

/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
typedef char *_QName;
#endif

#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (6)
typedef char *_XML;
#endif

#ifndef SOAP_TYPE_xsd__anySimpleType
#define SOAP_TYPE_xsd__anySimpleType (11)
typedef char *xsd__anySimpleType;
#endif

#ifndef SOAP_TYPE_cwmp__FaultCodeType
#define SOAP_TYPE_cwmp__FaultCodeType (13)
typedef char *cwmp__FaultCodeType;
#endif

#ifndef SOAP_TYPE_cwmp__ParameterKeyType
#define SOAP_TYPE_cwmp__ParameterKeyType (14)
typedef char *cwmp__ParameterKeyType;
#endif

#ifndef SOAP_TYPE_cwmp__CommandKeyType
#define SOAP_TYPE_cwmp__CommandKeyType (15)
typedef char *cwmp__CommandKeyType;
#endif

#ifndef SOAP_TYPE_cwmp__ObjectNameType
#define SOAP_TYPE_cwmp__ObjectNameType (16)
typedef char *cwmp__ObjectNameType;
#endif


/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Server-Side Operations                                                     *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 __cwmp__GetRPCMethods(struct soap*, struct _cwmp__GetRPCMethodsResponse *cwmp__GetRPCMethodsResponse);

SOAP_FMAC5 int SOAP_FMAC6 __cwmp__SetParameterValues(struct soap*, struct _cwmp__SetParameterValuesResponse *cwmp__SetParameterValuesResponse);

SOAP_FMAC5 int SOAP_FMAC6 __cwmp__GetParameterValues(struct soap*, struct _cwmp__GetParameterValuesResponse *cwmp__GetParameterValuesResponse);

SOAP_FMAC5 int SOAP_FMAC6 __cwmp__GetParameterNames(struct soap*, struct _cwmp__GetParameterNamesResponse *cwmp__GetParameterNamesResponse);

SOAP_FMAC5 int SOAP_FMAC6 __cwmp__SetParameterAttributes(struct soap*, struct _cwmp__SetParameterAttributesResponse *cwmp__SetParameterAttributesResponse);

SOAP_FMAC5 int SOAP_FMAC6 __cwmp__GetParameterAttributes(struct soap*, struct _cwmp__GetParameterAttributesResponse *cwmp__GetParameterAttributesResponse);

SOAP_FMAC5 int SOAP_FMAC6 __cwmp__AddObject(struct soap*, struct _cwmp__AddObjectResponse *cwmp__AddObjectResponse);

SOAP_FMAC5 int SOAP_FMAC6 __cwmp__DeleteObject(struct soap*, struct _cwmp__DeleteObjectResponse *cwmp__DeleteObjectResponse);

SOAP_FMAC5 int SOAP_FMAC6 __cwmp__Download(struct soap*, struct _cwmp__DownloadResponse *cwmp__DownloadResponse);

SOAP_FMAC5 int SOAP_FMAC6 __cwmp__Reboot(struct soap*, struct _cwmp__RebootResponse *cwmp__RebootResponse);

SOAP_FMAC5 int SOAP_FMAC6 __cwmp__GetQueuedTransfers(struct soap*, struct _cwmp__GetQueuedTransfersResponse *cwmp__GetQueuedTransfersResponse);

SOAP_FMAC5 int SOAP_FMAC6 __cwmp__ScheduleInform(struct soap*, struct _cwmp__ScheduleInformResponse *cwmp__ScheduleInformResponse);

SOAP_FMAC5 int SOAP_FMAC6 __cwmp__SetVouchers(struct soap*, struct _cwmp__SetVouchersResponse *cwmp__SetVouchersResponse);

SOAP_FMAC5 int SOAP_FMAC6 __cwmp__GetOptions(struct soap*, struct _cwmp__GetOptionsResponse *cwmp__GetOptionsResponse);

SOAP_FMAC5 int SOAP_FMAC6 __cwmp__Upload(struct soap*, struct _cwmp__UploadResponse *cwmp__UploadResponse);

SOAP_FMAC5 int SOAP_FMAC6 __cwmp__FactoryReset(struct soap*, struct _cwmp__FactoryResetResponse *cwmp__FactoryResetResponse);

SOAP_FMAC5 int SOAP_FMAC6 __cwmp__GetAllQueuedTransfers(struct soap*, struct _cwmp__GetAllQueuedTransfersResponse *cwmp__GetAllQueuedTransfersResponse);

SOAP_FMAC5 int SOAP_FMAC6 __cwmp__Inform(struct soap*, struct _cwmp__Inform *cwmp__Inform, struct _cwmp__InformResponse *cwmp__InformResponse);

SOAP_FMAC5 int SOAP_FMAC6 __cwmp__TransferComplete(struct soap*, struct _cwmp__TransferComplete *cwmp__TransferComplete, struct _cwmp__TransferCompleteResponse *cwmp__TransferCompleteResponse);

SOAP_FMAC5 int SOAP_FMAC6 __cwmp__AutonomousTransferComplete(struct soap*, struct _cwmp__AutonomousTransferComplete *cwmp__AutonomousTransferComplete, struct _cwmp__AutonomousTransferCompleteResponse *cwmp__AutonomousTransferCompleteResponse);

SOAP_FMAC5 int SOAP_FMAC6 __cwmp__Kicked(struct soap*, struct _cwmp__Kicked *cwmp__Kicked, struct _cwmp__KickedResponse *cwmp__KickedResponse);

SOAP_FMAC5 int SOAP_FMAC6 __cwmp__RequestDownload(struct soap*, struct _cwmp__RequestDownload *cwmp__RequestDownload, struct _cwmp__RequestDownloadResponse *cwmp__RequestDownloadResponse);

SOAP_FMAC5 int SOAP_FMAC6 __cwmp__Fault(struct soap*, struct _cwmp__Fault *cwmp__Fault);

SOAP_FMAC5 int SOAP_FMAC6 __cwmp__EmptyPost(struct soap*, struct _cwmp__Fault *cwmp__Fault, struct _cwmp__KickedResponse *cwmp__KickedResponse);

/******************************************************************************\
 *                                                                            *
 * Server-Side Skeletons to Invoke Service Operations                         *
 *                                                                            *
\******************************************************************************/

SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp__GetRPCMethods(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp__SetParameterValues(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp__GetParameterValues(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp__GetParameterNames(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp__SetParameterAttributes(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp__GetParameterAttributes(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp__AddObject(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp__DeleteObject(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp__Download(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp__Reboot(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp__GetQueuedTransfers(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp__ScheduleInform(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp__SetVouchers(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp__GetOptions(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp__Upload(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp__FactoryReset(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp__GetAllQueuedTransfers(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp__Inform(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp__TransferComplete(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp__AutonomousTransferComplete(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp__Kicked(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp__RequestDownload(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp__Fault(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp__EmptyPost(struct soap*);

/******************************************************************************\
 *                                                                            *
 * Client-Side Call Stubs                                                     *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 soap_send___cwmp__GetRPCMethods(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__GetRPCMethodsResponse *cwmp__GetRPCMethodsResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_recv___cwmp__GetRPCMethods(struct soap *soap, struct __cwmp__GetRPCMethods *_param_1);


SOAP_FMAC5 int SOAP_FMAC6 soap_send___cwmp__SetParameterValues(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__SetParameterValuesResponse *cwmp__SetParameterValuesResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_recv___cwmp__SetParameterValues(struct soap *soap, struct __cwmp__SetParameterValues *_param_2);


SOAP_FMAC5 int SOAP_FMAC6 soap_send___cwmp__GetParameterValues(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__GetParameterValuesResponse *cwmp__GetParameterValuesResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_recv___cwmp__GetParameterValues(struct soap *soap, struct __cwmp__GetParameterValues *_param_3);


SOAP_FMAC5 int SOAP_FMAC6 soap_send___cwmp__GetParameterNames(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__GetParameterNamesResponse *cwmp__GetParameterNamesResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_recv___cwmp__GetParameterNames(struct soap *soap, struct __cwmp__GetParameterNames *_param_4);


SOAP_FMAC5 int SOAP_FMAC6 soap_send___cwmp__SetParameterAttributes(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__SetParameterAttributesResponse *cwmp__SetParameterAttributesResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_recv___cwmp__SetParameterAttributes(struct soap *soap, struct __cwmp__SetParameterAttributes *_param_5);


SOAP_FMAC5 int SOAP_FMAC6 soap_send___cwmp__GetParameterAttributes(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__GetParameterAttributesResponse *cwmp__GetParameterAttributesResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_recv___cwmp__GetParameterAttributes(struct soap *soap, struct __cwmp__GetParameterAttributes *_param_6);


SOAP_FMAC5 int SOAP_FMAC6 soap_send___cwmp__AddObject(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__AddObjectResponse *cwmp__AddObjectResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_recv___cwmp__AddObject(struct soap *soap, struct __cwmp__AddObject *_param_7);


SOAP_FMAC5 int SOAP_FMAC6 soap_send___cwmp__DeleteObject(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__DeleteObjectResponse *cwmp__DeleteObjectResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_recv___cwmp__DeleteObject(struct soap *soap, struct __cwmp__DeleteObject *_param_8);


SOAP_FMAC5 int SOAP_FMAC6 soap_send___cwmp__Download(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__DownloadResponse *cwmp__DownloadResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_recv___cwmp__Download(struct soap *soap, struct __cwmp__Download *_param_9);


SOAP_FMAC5 int SOAP_FMAC6 soap_send___cwmp__Reboot(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__RebootResponse *cwmp__RebootResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_recv___cwmp__Reboot(struct soap *soap, struct __cwmp__Reboot *_param_10);


SOAP_FMAC5 int SOAP_FMAC6 soap_send___cwmp__GetQueuedTransfers(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__GetQueuedTransfersResponse *cwmp__GetQueuedTransfersResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_recv___cwmp__GetQueuedTransfers(struct soap *soap, struct __cwmp__GetQueuedTransfers *_param_11);


SOAP_FMAC5 int SOAP_FMAC6 soap_send___cwmp__ScheduleInform(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__ScheduleInformResponse *cwmp__ScheduleInformResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_recv___cwmp__ScheduleInform(struct soap *soap, struct __cwmp__ScheduleInform *_param_12);


SOAP_FMAC5 int SOAP_FMAC6 soap_send___cwmp__SetVouchers(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__SetVouchersResponse *cwmp__SetVouchersResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_recv___cwmp__SetVouchers(struct soap *soap, struct __cwmp__SetVouchers *_param_13);


SOAP_FMAC5 int SOAP_FMAC6 soap_send___cwmp__GetOptions(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__GetOptionsResponse *cwmp__GetOptionsResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_recv___cwmp__GetOptions(struct soap *soap, struct __cwmp__GetOptions *_param_14);


SOAP_FMAC5 int SOAP_FMAC6 soap_send___cwmp__Upload(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__UploadResponse *cwmp__UploadResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_recv___cwmp__Upload(struct soap *soap, struct __cwmp__Upload *_param_15);


SOAP_FMAC5 int SOAP_FMAC6 soap_send___cwmp__FactoryReset(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__FactoryResetResponse *cwmp__FactoryResetResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_recv___cwmp__FactoryReset(struct soap *soap, struct __cwmp__FactoryReset *_param_16);


SOAP_FMAC5 int SOAP_FMAC6 soap_send___cwmp__GetAllQueuedTransfers(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__GetAllQueuedTransfersResponse *cwmp__GetAllQueuedTransfersResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_recv___cwmp__GetAllQueuedTransfers(struct soap *soap, struct __cwmp__GetAllQueuedTransfers *_param_17);


SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp__Inform(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__Inform *cwmp__Inform, struct _cwmp__InformResponse *cwmp__InformResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp__TransferComplete(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__TransferComplete *cwmp__TransferComplete, struct _cwmp__TransferCompleteResponse *cwmp__TransferCompleteResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp__AutonomousTransferComplete(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__AutonomousTransferComplete *cwmp__AutonomousTransferComplete, struct _cwmp__AutonomousTransferCompleteResponse *cwmp__AutonomousTransferCompleteResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp__Kicked(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__Kicked *cwmp__Kicked, struct _cwmp__KickedResponse *cwmp__KickedResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp__RequestDownload(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__RequestDownload *cwmp__RequestDownload, struct _cwmp__RequestDownloadResponse *cwmp__RequestDownloadResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_send___cwmp__Fault(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__Fault *cwmp__Fault);

SOAP_FMAC5 int SOAP_FMAC6 soap_recv___cwmp__Fault(struct soap *soap, struct __cwmp__Fault *_param_18);


SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp__EmptyPost(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__Fault *cwmp__Fault, struct _cwmp__KickedResponse *cwmp__KickedResponse);

#ifdef __cplusplus
}
#endif

#endif

/* End of soapStub.h */
