/* soapClient.c
   Generated by gSOAP 2.8.5 from cwmp-1-1.h

Copyright(C) 2000-2011, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) soapClient.c ver 2.8.5 2011-12-14 08:23:26 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_send___cwmp__GetRPCMethods(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__GetRPCMethodsResponse *cwmp__GetRPCMethodsResponse)
{	struct __cwmp__GetRPCMethods soap_tmp___cwmp__GetRPCMethods;
	if (!soap_action)
		soap_action = "urn:dslforum-org:cwmp-1-1:getRPCMethodsIn";
	soap->encodingStyle = NULL;
	soap_tmp___cwmp__GetRPCMethods.cwmp__GetRPCMethodsResponse = cwmp__GetRPCMethodsResponse;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___cwmp__GetRPCMethods(soap, &soap_tmp___cwmp__GetRPCMethods);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___cwmp__GetRPCMethods(soap, &soap_tmp___cwmp__GetRPCMethods, "-cwmp:GetRPCMethods", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___cwmp__GetRPCMethods(soap, &soap_tmp___cwmp__GetRPCMethods, "-cwmp:GetRPCMethods", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_recv___cwmp__GetRPCMethods(struct soap *soap, struct __cwmp__GetRPCMethods *_param_1)
{
	soap_default___cwmp__GetRPCMethods(soap, _param_1);
	soap_begin(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get___cwmp__GetRPCMethods(soap, _param_1, "-cwmp:GetRPCMethods", NULL);
	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
		soap->error = SOAP_NO_METHOD;
	if (soap->error
	 || soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_send___cwmp__SetParameterValues(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__SetParameterValuesResponse *cwmp__SetParameterValuesResponse)
{	struct __cwmp__SetParameterValues soap_tmp___cwmp__SetParameterValues;
	if (!soap_action)
		soap_action = "urn:dslforum-org:cwmp-1-1:setParameterValuesIn";
	soap->encodingStyle = NULL;
	soap_tmp___cwmp__SetParameterValues.cwmp__SetParameterValuesResponse = cwmp__SetParameterValuesResponse;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___cwmp__SetParameterValues(soap, &soap_tmp___cwmp__SetParameterValues);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___cwmp__SetParameterValues(soap, &soap_tmp___cwmp__SetParameterValues, "-cwmp:SetParameterValues", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___cwmp__SetParameterValues(soap, &soap_tmp___cwmp__SetParameterValues, "-cwmp:SetParameterValues", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_recv___cwmp__SetParameterValues(struct soap *soap, struct __cwmp__SetParameterValues *_param_2)
{
	soap_default___cwmp__SetParameterValues(soap, _param_2);
	soap_begin(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get___cwmp__SetParameterValues(soap, _param_2, "-cwmp:SetParameterValues", NULL);
	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
		soap->error = SOAP_NO_METHOD;
	if (soap->error
	 || soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_send___cwmp__GetParameterValues(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__GetParameterValuesResponse *cwmp__GetParameterValuesResponse)
{	struct __cwmp__GetParameterValues soap_tmp___cwmp__GetParameterValues;
	if (!soap_action)
		soap_action = "urn:dslforum-org:cwmp-1-1:getParameterValuesIn";
	soap->encodingStyle = NULL;
	soap_tmp___cwmp__GetParameterValues.cwmp__GetParameterValuesResponse = cwmp__GetParameterValuesResponse;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___cwmp__GetParameterValues(soap, &soap_tmp___cwmp__GetParameterValues);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___cwmp__GetParameterValues(soap, &soap_tmp___cwmp__GetParameterValues, "-cwmp:GetParameterValues", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___cwmp__GetParameterValues(soap, &soap_tmp___cwmp__GetParameterValues, "-cwmp:GetParameterValues", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_recv___cwmp__GetParameterValues(struct soap *soap, struct __cwmp__GetParameterValues *_param_3)
{
	soap_default___cwmp__GetParameterValues(soap, _param_3);
	soap_begin(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get___cwmp__GetParameterValues(soap, _param_3, "-cwmp:GetParameterValues", NULL);
	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
		soap->error = SOAP_NO_METHOD;
	if (soap->error
	 || soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_send___cwmp__GetParameterNames(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__GetParameterNamesResponse *cwmp__GetParameterNamesResponse)
{	struct __cwmp__GetParameterNames soap_tmp___cwmp__GetParameterNames;
	if (!soap_action)
		soap_action = "urn:dslforum-org:cwmp-1-1:getParameterNamesIn";
	soap->encodingStyle = NULL;
	soap_tmp___cwmp__GetParameterNames.cwmp__GetParameterNamesResponse = cwmp__GetParameterNamesResponse;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___cwmp__GetParameterNames(soap, &soap_tmp___cwmp__GetParameterNames);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___cwmp__GetParameterNames(soap, &soap_tmp___cwmp__GetParameterNames, "-cwmp:GetParameterNames", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___cwmp__GetParameterNames(soap, &soap_tmp___cwmp__GetParameterNames, "-cwmp:GetParameterNames", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_recv___cwmp__GetParameterNames(struct soap *soap, struct __cwmp__GetParameterNames *_param_4)
{
	soap_default___cwmp__GetParameterNames(soap, _param_4);
	soap_begin(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get___cwmp__GetParameterNames(soap, _param_4, "-cwmp:GetParameterNames", NULL);
	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
		soap->error = SOAP_NO_METHOD;
	if (soap->error
	 || soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_send___cwmp__SetParameterAttributes(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__SetParameterAttributesResponse *cwmp__SetParameterAttributesResponse)
{	struct __cwmp__SetParameterAttributes soap_tmp___cwmp__SetParameterAttributes;
	if (!soap_action)
		soap_action = "urn:dslforum-org:cwmp-1-1:setParameterAttributesIn";
	soap->encodingStyle = NULL;
	soap_tmp___cwmp__SetParameterAttributes.cwmp__SetParameterAttributesResponse = cwmp__SetParameterAttributesResponse;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___cwmp__SetParameterAttributes(soap, &soap_tmp___cwmp__SetParameterAttributes);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___cwmp__SetParameterAttributes(soap, &soap_tmp___cwmp__SetParameterAttributes, "-cwmp:SetParameterAttributes", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___cwmp__SetParameterAttributes(soap, &soap_tmp___cwmp__SetParameterAttributes, "-cwmp:SetParameterAttributes", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_recv___cwmp__SetParameterAttributes(struct soap *soap, struct __cwmp__SetParameterAttributes *_param_5)
{
	soap_default___cwmp__SetParameterAttributes(soap, _param_5);
	soap_begin(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get___cwmp__SetParameterAttributes(soap, _param_5, "-cwmp:SetParameterAttributes", NULL);
	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
		soap->error = SOAP_NO_METHOD;
	if (soap->error
	 || soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_send___cwmp__GetParameterAttributes(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__GetParameterAttributesResponse *cwmp__GetParameterAttributesResponse)
{	struct __cwmp__GetParameterAttributes soap_tmp___cwmp__GetParameterAttributes;
	if (!soap_action)
		soap_action = "urn:dslforum-org:cwmp-1-1:getParameterAttributesIn";
	soap->encodingStyle = NULL;
	soap_tmp___cwmp__GetParameterAttributes.cwmp__GetParameterAttributesResponse = cwmp__GetParameterAttributesResponse;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___cwmp__GetParameterAttributes(soap, &soap_tmp___cwmp__GetParameterAttributes);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___cwmp__GetParameterAttributes(soap, &soap_tmp___cwmp__GetParameterAttributes, "-cwmp:GetParameterAttributes", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___cwmp__GetParameterAttributes(soap, &soap_tmp___cwmp__GetParameterAttributes, "-cwmp:GetParameterAttributes", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_recv___cwmp__GetParameterAttributes(struct soap *soap, struct __cwmp__GetParameterAttributes *_param_6)
{
	soap_default___cwmp__GetParameterAttributes(soap, _param_6);
	soap_begin(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get___cwmp__GetParameterAttributes(soap, _param_6, "-cwmp:GetParameterAttributes", NULL);
	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
		soap->error = SOAP_NO_METHOD;
	if (soap->error
	 || soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_send___cwmp__AddObject(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__AddObjectResponse *cwmp__AddObjectResponse)
{	struct __cwmp__AddObject soap_tmp___cwmp__AddObject;
	if (!soap_action)
		soap_action = "urn:dslforum-org:cwmp-1-1:addObjectIn";
	soap->encodingStyle = NULL;
	soap_tmp___cwmp__AddObject.cwmp__AddObjectResponse = cwmp__AddObjectResponse;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___cwmp__AddObject(soap, &soap_tmp___cwmp__AddObject);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___cwmp__AddObject(soap, &soap_tmp___cwmp__AddObject, "-cwmp:AddObject", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___cwmp__AddObject(soap, &soap_tmp___cwmp__AddObject, "-cwmp:AddObject", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_recv___cwmp__AddObject(struct soap *soap, struct __cwmp__AddObject *_param_7)
{
	soap_default___cwmp__AddObject(soap, _param_7);
	soap_begin(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get___cwmp__AddObject(soap, _param_7, "-cwmp:AddObject", NULL);
	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
		soap->error = SOAP_NO_METHOD;
	if (soap->error
	 || soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_send___cwmp__DeleteObject(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__DeleteObjectResponse *cwmp__DeleteObjectResponse)
{	struct __cwmp__DeleteObject soap_tmp___cwmp__DeleteObject;
	if (!soap_action)
		soap_action = "urn:dslforum-org:cwmp-1-1:deleteObjectIn";
	soap->encodingStyle = NULL;
	soap_tmp___cwmp__DeleteObject.cwmp__DeleteObjectResponse = cwmp__DeleteObjectResponse;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___cwmp__DeleteObject(soap, &soap_tmp___cwmp__DeleteObject);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___cwmp__DeleteObject(soap, &soap_tmp___cwmp__DeleteObject, "-cwmp:DeleteObject", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___cwmp__DeleteObject(soap, &soap_tmp___cwmp__DeleteObject, "-cwmp:DeleteObject", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_recv___cwmp__DeleteObject(struct soap *soap, struct __cwmp__DeleteObject *_param_8)
{
	soap_default___cwmp__DeleteObject(soap, _param_8);
	soap_begin(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get___cwmp__DeleteObject(soap, _param_8, "-cwmp:DeleteObject", NULL);
	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
		soap->error = SOAP_NO_METHOD;
	if (soap->error
	 || soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_send___cwmp__Download(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__DownloadResponse *cwmp__DownloadResponse)
{	struct __cwmp__Download soap_tmp___cwmp__Download;
	if (!soap_action)
		soap_action = "urn:dslforum-org:cwmp-1-1:downloadIn";
	soap->encodingStyle = NULL;
	soap_tmp___cwmp__Download.cwmp__DownloadResponse = cwmp__DownloadResponse;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___cwmp__Download(soap, &soap_tmp___cwmp__Download);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___cwmp__Download(soap, &soap_tmp___cwmp__Download, "-cwmp:Download", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___cwmp__Download(soap, &soap_tmp___cwmp__Download, "-cwmp:Download", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_recv___cwmp__Download(struct soap *soap, struct __cwmp__Download *_param_9)
{
	soap_default___cwmp__Download(soap, _param_9);
	soap_begin(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get___cwmp__Download(soap, _param_9, "-cwmp:Download", NULL);
	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
		soap->error = SOAP_NO_METHOD;
	if (soap->error
	 || soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_send___cwmp__Reboot(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__RebootResponse *cwmp__RebootResponse)
{	struct __cwmp__Reboot soap_tmp___cwmp__Reboot;
	if (!soap_action)
		soap_action = "urn:dslforum-org:cwmp-1-1:rebootIn";
	soap->encodingStyle = NULL;
	soap_tmp___cwmp__Reboot.cwmp__RebootResponse = cwmp__RebootResponse;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___cwmp__Reboot(soap, &soap_tmp___cwmp__Reboot);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___cwmp__Reboot(soap, &soap_tmp___cwmp__Reboot, "-cwmp:Reboot", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___cwmp__Reboot(soap, &soap_tmp___cwmp__Reboot, "-cwmp:Reboot", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_recv___cwmp__Reboot(struct soap *soap, struct __cwmp__Reboot *_param_10)
{
	soap_default___cwmp__Reboot(soap, _param_10);
	soap_begin(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get___cwmp__Reboot(soap, _param_10, "-cwmp:Reboot", NULL);
	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
		soap->error = SOAP_NO_METHOD;
	if (soap->error
	 || soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_send___cwmp__GetQueuedTransfers(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__GetQueuedTransfersResponse *cwmp__GetQueuedTransfersResponse)
{	struct __cwmp__GetQueuedTransfers soap_tmp___cwmp__GetQueuedTransfers;
	if (!soap_action)
		soap_action = "urn:dslforum-org:cwmp-1-1:getQueuedTransfersIn";
	soap->encodingStyle = NULL;
	soap_tmp___cwmp__GetQueuedTransfers.cwmp__GetQueuedTransfersResponse = cwmp__GetQueuedTransfersResponse;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___cwmp__GetQueuedTransfers(soap, &soap_tmp___cwmp__GetQueuedTransfers);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___cwmp__GetQueuedTransfers(soap, &soap_tmp___cwmp__GetQueuedTransfers, "-cwmp:GetQueuedTransfers", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___cwmp__GetQueuedTransfers(soap, &soap_tmp___cwmp__GetQueuedTransfers, "-cwmp:GetQueuedTransfers", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_recv___cwmp__GetQueuedTransfers(struct soap *soap, struct __cwmp__GetQueuedTransfers *_param_11)
{
	soap_default___cwmp__GetQueuedTransfers(soap, _param_11);
	soap_begin(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get___cwmp__GetQueuedTransfers(soap, _param_11, "-cwmp:GetQueuedTransfers", NULL);
	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
		soap->error = SOAP_NO_METHOD;
	if (soap->error
	 || soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_send___cwmp__ScheduleInform(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__ScheduleInformResponse *cwmp__ScheduleInformResponse)
{	struct __cwmp__ScheduleInform soap_tmp___cwmp__ScheduleInform;
	if (!soap_action)
		soap_action = "urn:dslforum-org:cwmp-1-1:scheduleInformIn";
	soap->encodingStyle = NULL;
	soap_tmp___cwmp__ScheduleInform.cwmp__ScheduleInformResponse = cwmp__ScheduleInformResponse;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___cwmp__ScheduleInform(soap, &soap_tmp___cwmp__ScheduleInform);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___cwmp__ScheduleInform(soap, &soap_tmp___cwmp__ScheduleInform, "-cwmp:ScheduleInform", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___cwmp__ScheduleInform(soap, &soap_tmp___cwmp__ScheduleInform, "-cwmp:ScheduleInform", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_recv___cwmp__ScheduleInform(struct soap *soap, struct __cwmp__ScheduleInform *_param_12)
{
	soap_default___cwmp__ScheduleInform(soap, _param_12);
	soap_begin(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get___cwmp__ScheduleInform(soap, _param_12, "-cwmp:ScheduleInform", NULL);
	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
		soap->error = SOAP_NO_METHOD;
	if (soap->error
	 || soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_send___cwmp__SetVouchers(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__SetVouchersResponse *cwmp__SetVouchersResponse)
{	struct __cwmp__SetVouchers soap_tmp___cwmp__SetVouchers;
	if (!soap_action)
		soap_action = "urn:dslforum-org:cwmp-1-1:setVouchersIn";
	soap->encodingStyle = NULL;
	soap_tmp___cwmp__SetVouchers.cwmp__SetVouchersResponse = cwmp__SetVouchersResponse;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___cwmp__SetVouchers(soap, &soap_tmp___cwmp__SetVouchers);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___cwmp__SetVouchers(soap, &soap_tmp___cwmp__SetVouchers, "-cwmp:SetVouchers", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___cwmp__SetVouchers(soap, &soap_tmp___cwmp__SetVouchers, "-cwmp:SetVouchers", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_recv___cwmp__SetVouchers(struct soap *soap, struct __cwmp__SetVouchers *_param_13)
{
	soap_default___cwmp__SetVouchers(soap, _param_13);
	soap_begin(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get___cwmp__SetVouchers(soap, _param_13, "-cwmp:SetVouchers", NULL);
	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
		soap->error = SOAP_NO_METHOD;
	if (soap->error
	 || soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_send___cwmp__GetOptions(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__GetOptionsResponse *cwmp__GetOptionsResponse)
{	struct __cwmp__GetOptions soap_tmp___cwmp__GetOptions;
	if (!soap_action)
		soap_action = "urn:dslforum-org:cwmp-1-1:getOptionsIn";
	soap->encodingStyle = NULL;
	soap_tmp___cwmp__GetOptions.cwmp__GetOptionsResponse = cwmp__GetOptionsResponse;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___cwmp__GetOptions(soap, &soap_tmp___cwmp__GetOptions);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___cwmp__GetOptions(soap, &soap_tmp___cwmp__GetOptions, "-cwmp:GetOptions", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___cwmp__GetOptions(soap, &soap_tmp___cwmp__GetOptions, "-cwmp:GetOptions", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_recv___cwmp__GetOptions(struct soap *soap, struct __cwmp__GetOptions *_param_14)
{
	soap_default___cwmp__GetOptions(soap, _param_14);
	soap_begin(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get___cwmp__GetOptions(soap, _param_14, "-cwmp:GetOptions", NULL);
	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
		soap->error = SOAP_NO_METHOD;
	if (soap->error
	 || soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_send___cwmp__Upload(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__UploadResponse *cwmp__UploadResponse)
{	struct __cwmp__Upload soap_tmp___cwmp__Upload;
	if (!soap_action)
		soap_action = "urn:dslforum-org:cwmp-1-1:uploadIn";
	soap->encodingStyle = NULL;
	soap_tmp___cwmp__Upload.cwmp__UploadResponse = cwmp__UploadResponse;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___cwmp__Upload(soap, &soap_tmp___cwmp__Upload);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___cwmp__Upload(soap, &soap_tmp___cwmp__Upload, "-cwmp:Upload", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___cwmp__Upload(soap, &soap_tmp___cwmp__Upload, "-cwmp:Upload", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_recv___cwmp__Upload(struct soap *soap, struct __cwmp__Upload *_param_15)
{
	soap_default___cwmp__Upload(soap, _param_15);
	soap_begin(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get___cwmp__Upload(soap, _param_15, "-cwmp:Upload", NULL);
	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
		soap->error = SOAP_NO_METHOD;
	if (soap->error
	 || soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_send___cwmp__FactoryReset(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__FactoryResetResponse *cwmp__FactoryResetResponse)
{	struct __cwmp__FactoryReset soap_tmp___cwmp__FactoryReset;
	if (!soap_action)
		soap_action = "urn:dslforum-org:cwmp-1-1:factoryResetIn";
	soap->encodingStyle = NULL;
	soap_tmp___cwmp__FactoryReset.cwmp__FactoryResetResponse = cwmp__FactoryResetResponse;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___cwmp__FactoryReset(soap, &soap_tmp___cwmp__FactoryReset);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___cwmp__FactoryReset(soap, &soap_tmp___cwmp__FactoryReset, "-cwmp:FactoryReset", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___cwmp__FactoryReset(soap, &soap_tmp___cwmp__FactoryReset, "-cwmp:FactoryReset", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_recv___cwmp__FactoryReset(struct soap *soap, struct __cwmp__FactoryReset *_param_16)
{
	soap_default___cwmp__FactoryReset(soap, _param_16);
	soap_begin(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get___cwmp__FactoryReset(soap, _param_16, "-cwmp:FactoryReset", NULL);
	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
		soap->error = SOAP_NO_METHOD;
	if (soap->error
	 || soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_send___cwmp__GetAllQueuedTransfers(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__GetAllQueuedTransfersResponse *cwmp__GetAllQueuedTransfersResponse)
{	struct __cwmp__GetAllQueuedTransfers soap_tmp___cwmp__GetAllQueuedTransfers;
	if (!soap_action)
		soap_action = "urn:dslforum-org:cwmp-1-1:getAllQueuedTransfersIn";
	soap->encodingStyle = NULL;
	soap_tmp___cwmp__GetAllQueuedTransfers.cwmp__GetAllQueuedTransfersResponse = cwmp__GetAllQueuedTransfersResponse;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___cwmp__GetAllQueuedTransfers(soap, &soap_tmp___cwmp__GetAllQueuedTransfers);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___cwmp__GetAllQueuedTransfers(soap, &soap_tmp___cwmp__GetAllQueuedTransfers, "-cwmp:GetAllQueuedTransfers", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___cwmp__GetAllQueuedTransfers(soap, &soap_tmp___cwmp__GetAllQueuedTransfers, "-cwmp:GetAllQueuedTransfers", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_recv___cwmp__GetAllQueuedTransfers(struct soap *soap, struct __cwmp__GetAllQueuedTransfers *_param_17)
{
	soap_default___cwmp__GetAllQueuedTransfers(soap, _param_17);
	soap_begin(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get___cwmp__GetAllQueuedTransfers(soap, _param_17, "-cwmp:GetAllQueuedTransfers", NULL);
	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
		soap->error = SOAP_NO_METHOD;
	if (soap->error
	 || soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp__Inform(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__Inform *cwmp__Inform, struct _cwmp__InformResponse *cwmp__InformResponse)
{	struct __cwmp__Inform soap_tmp___cwmp__Inform;
	if (!soap_action)
		soap_action = "urn:dslforum-org:cwmp-1-1:informIn";
	soap->encodingStyle = NULL;
	soap_tmp___cwmp__Inform.cwmp__Inform = cwmp__Inform;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___cwmp__Inform(soap, &soap_tmp___cwmp__Inform);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___cwmp__Inform(soap, &soap_tmp___cwmp__Inform, "-cwmp:Inform", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___cwmp__Inform(soap, &soap_tmp___cwmp__Inform, "-cwmp:Inform", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!cwmp__InformResponse)
		return soap_closesock(soap);
	soap_default__cwmp__InformResponse(soap, cwmp__InformResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__cwmp__InformResponse(soap, cwmp__InformResponse, "cwmp:InformResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp__TransferComplete(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__TransferComplete *cwmp__TransferComplete, struct _cwmp__TransferCompleteResponse *cwmp__TransferCompleteResponse)
{	struct __cwmp__TransferComplete soap_tmp___cwmp__TransferComplete;
	if (!soap_action)
		soap_action = "urn:dslforum-org:cwmp-1-1:transferCompleteIn";
	soap->encodingStyle = NULL;
	soap_tmp___cwmp__TransferComplete.cwmp__TransferComplete = cwmp__TransferComplete;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___cwmp__TransferComplete(soap, &soap_tmp___cwmp__TransferComplete);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___cwmp__TransferComplete(soap, &soap_tmp___cwmp__TransferComplete, "-cwmp:TransferComplete", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___cwmp__TransferComplete(soap, &soap_tmp___cwmp__TransferComplete, "-cwmp:TransferComplete", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!cwmp__TransferCompleteResponse)
		return soap_closesock(soap);
	soap_default__cwmp__TransferCompleteResponse(soap, cwmp__TransferCompleteResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__cwmp__TransferCompleteResponse(soap, cwmp__TransferCompleteResponse, "cwmp:TransferCompleteResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp__AutonomousTransferComplete(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__AutonomousTransferComplete *cwmp__AutonomousTransferComplete, struct _cwmp__AutonomousTransferCompleteResponse *cwmp__AutonomousTransferCompleteResponse)
{	struct __cwmp__AutonomousTransferComplete soap_tmp___cwmp__AutonomousTransferComplete;
	if (!soap_action)
		soap_action = "urn:dslforum-org:cwmp-1-1:autonomousTransferCompleteIn";
	soap->encodingStyle = NULL;
	soap_tmp___cwmp__AutonomousTransferComplete.cwmp__AutonomousTransferComplete = cwmp__AutonomousTransferComplete;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___cwmp__AutonomousTransferComplete(soap, &soap_tmp___cwmp__AutonomousTransferComplete);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___cwmp__AutonomousTransferComplete(soap, &soap_tmp___cwmp__AutonomousTransferComplete, "-cwmp:AutonomousTransferComplete", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___cwmp__AutonomousTransferComplete(soap, &soap_tmp___cwmp__AutonomousTransferComplete, "-cwmp:AutonomousTransferComplete", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!cwmp__AutonomousTransferCompleteResponse)
		return soap_closesock(soap);
	soap_default__cwmp__AutonomousTransferCompleteResponse(soap, cwmp__AutonomousTransferCompleteResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__cwmp__AutonomousTransferCompleteResponse(soap, cwmp__AutonomousTransferCompleteResponse, "cwmp:AutonomousTransferCompleteResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp__Kicked(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__Kicked *cwmp__Kicked, struct _cwmp__KickedResponse *cwmp__KickedResponse)
{	struct __cwmp__Kicked soap_tmp___cwmp__Kicked;
	if (!soap_action)
		soap_action = "urn:dslforum-org:cwmp-1-1:kickedIn";
	soap->encodingStyle = NULL;
	soap_tmp___cwmp__Kicked.cwmp__Kicked = cwmp__Kicked;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___cwmp__Kicked(soap, &soap_tmp___cwmp__Kicked);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___cwmp__Kicked(soap, &soap_tmp___cwmp__Kicked, "-cwmp:Kicked", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___cwmp__Kicked(soap, &soap_tmp___cwmp__Kicked, "-cwmp:Kicked", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!cwmp__KickedResponse)
		return soap_closesock(soap);
	soap_default__cwmp__KickedResponse(soap, cwmp__KickedResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__cwmp__KickedResponse(soap, cwmp__KickedResponse, "cwmp:KickedResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp__RequestDownload(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__RequestDownload *cwmp__RequestDownload, struct _cwmp__RequestDownloadResponse *cwmp__RequestDownloadResponse)
{	struct __cwmp__RequestDownload soap_tmp___cwmp__RequestDownload;
	if (!soap_action)
		soap_action = "urn:dslforum-org:cwmp-1-1:requestDownloadIn";
	soap->encodingStyle = NULL;
	soap_tmp___cwmp__RequestDownload.cwmp__RequestDownload = cwmp__RequestDownload;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___cwmp__RequestDownload(soap, &soap_tmp___cwmp__RequestDownload);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___cwmp__RequestDownload(soap, &soap_tmp___cwmp__RequestDownload, "-cwmp:RequestDownload", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___cwmp__RequestDownload(soap, &soap_tmp___cwmp__RequestDownload, "-cwmp:RequestDownload", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!cwmp__RequestDownloadResponse)
		return soap_closesock(soap);
	soap_default__cwmp__RequestDownloadResponse(soap, cwmp__RequestDownloadResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__cwmp__RequestDownloadResponse(soap, cwmp__RequestDownloadResponse, "cwmp:RequestDownloadResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_send___cwmp__Fault(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__Fault *cwmp__Fault)
{	struct __cwmp__Fault soap_tmp___cwmp__Fault;
	if (!soap_action)
		soap_action = "urn:dslforum-org:cwmp-1-1:faultIn";
	soap->encodingStyle = NULL;
	soap_tmp___cwmp__Fault.cwmp__Fault = cwmp__Fault;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___cwmp__Fault(soap, &soap_tmp___cwmp__Fault);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___cwmp__Fault(soap, &soap_tmp___cwmp__Fault, "-cwmp:Fault", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___cwmp__Fault(soap, &soap_tmp___cwmp__Fault, "-cwmp:Fault", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_recv___cwmp__Fault(struct soap *soap, struct __cwmp__Fault *_param_18)
{
	soap_default___cwmp__Fault(soap, _param_18);
	soap_begin(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get___cwmp__Fault(soap, _param_18, "-cwmp:Fault", NULL);
	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
		soap->error = SOAP_NO_METHOD;
	if (soap->error
	 || soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp__EmptyPost(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__Fault *cwmp__Fault, struct _cwmp__KickedResponse *cwmp__KickedResponse)
{	struct __cwmp__EmptyPost soap_tmp___cwmp__EmptyPost;
	if (!soap_action)
		soap_action = "urn:EmptyPost";
	soap->encodingStyle = NULL;
	soap_tmp___cwmp__EmptyPost.cwmp__Fault = cwmp__Fault;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___cwmp__EmptyPost(soap, &soap_tmp___cwmp__EmptyPost);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___cwmp__EmptyPost(soap, &soap_tmp___cwmp__EmptyPost, "-cwmp:EmptyPost", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___cwmp__EmptyPost(soap, &soap_tmp___cwmp__EmptyPost, "-cwmp:EmptyPost", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!cwmp__KickedResponse)
		return soap_closesock(soap);
	soap_default__cwmp__KickedResponse(soap, cwmp__KickedResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__cwmp__KickedResponse(soap, cwmp__KickedResponse, "cwmp:KickedResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

#ifdef __cplusplus
}
#endif

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapClient.c */
