/* soapServer.c
   Generated by gSOAP 2.8.5 from cwmp-1-1.h

Copyright(C) 2000-2011, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) soapServer.c ver 2.8.5 2011-12-14 07:04:19 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap *soap, const char *soap_endpoint)
{
	unsigned int k = soap->max_keep_alive;

	do
	{
		if (soap->max_keep_alive > 0 && !--k)
			soap->keep_alive = 0;

		if (soap_begin_serve(soap))
		{	if (soap->error >= SOAP_STOP)
				continue;
			return soap->error;
		}
		if (soap_serve_request(soap, soap_endpoint) || (soap->fserveloop && soap->fserveloop(soap)))
		{
			return soap_send_fault(soap);
		}

	} while (soap->keep_alive);

	return SOAP_OK;
}

#ifndef WITH_NOSERVEREQUEST
SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap *soap, const char *soap_endpoint)
{
	soap_peek_element(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp:GetRPCMethods"))
		return soap_serve___cwmp__GetRPCMethods(soap, soap_endpoint);
	if (!soap_match_tag(soap, soap->tag, "cwmp:SetParameterValues"))
		return soap_serve___cwmp__SetParameterValues(soap, soap_endpoint);
	if (!soap_match_tag(soap, soap->tag, "cwmp:GetParameterValues"))
		return soap_serve___cwmp__GetParameterValues(soap, soap_endpoint);
	if (!soap_match_tag(soap, soap->tag, "cwmp:GetParameterNames"))
		return soap_serve___cwmp__GetParameterNames(soap, soap_endpoint);
	if (!soap_match_tag(soap, soap->tag, "cwmp:SetParameterAttributes"))
		return soap_serve___cwmp__SetParameterAttributes(soap, soap_endpoint);
	if (!soap_match_tag(soap, soap->tag, "cwmp:GetParameterAttributes"))
		return soap_serve___cwmp__GetParameterAttributes(soap, soap_endpoint);
	if (!soap_match_tag(soap, soap->tag, "cwmp:AddObject"))
		return soap_serve___cwmp__AddObject(soap, soap_endpoint);
	if (!soap_match_tag(soap, soap->tag, "cwmp:DeleteObject"))
		return soap_serve___cwmp__DeleteObject(soap, soap_endpoint);
	if (!soap_match_tag(soap, soap->tag, "cwmp:Download"))
		return soap_serve___cwmp__Download(soap, soap_endpoint);
	if (!soap_match_tag(soap, soap->tag, "cwmp:Reboot"))
		return soap_serve___cwmp__Reboot(soap, soap_endpoint);
	if (!soap_match_tag(soap, soap->tag, "cwmp:GetQueuedTransfers"))
		return soap_serve___cwmp__GetQueuedTransfers(soap, soap_endpoint);
	if (!soap_match_tag(soap, soap->tag, "cwmp:ScheduleInform"))
		return soap_serve___cwmp__ScheduleInform(soap, soap_endpoint);
	if (!soap_match_tag(soap, soap->tag, "cwmp:SetVouchers"))
		return soap_serve___cwmp__SetVouchers(soap, soap_endpoint);
	if (!soap_match_tag(soap, soap->tag, "cwmp:GetOptions"))
		return soap_serve___cwmp__GetOptions(soap, soap_endpoint);
	if (!soap_match_tag(soap, soap->tag, "cwmp:Upload"))
		return soap_serve___cwmp__Upload(soap, soap_endpoint);
	if (!soap_match_tag(soap, soap->tag, "cwmp:FactoryReset"))
		return soap_serve___cwmp__FactoryReset(soap, soap_endpoint);
	if (!soap_match_tag(soap, soap->tag, "cwmp:GetAllQueuedTransfers"))
		return soap_serve___cwmp__GetAllQueuedTransfers(soap, soap_endpoint);
	if (!soap_match_tag(soap, soap->tag, "cwmp:Fault"))
		return soap_serve___cwmp__Fault(soap);
	return soap->error = SOAP_NO_METHOD;
}
#endif

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp__GetRPCMethods(struct soap *soap, const char *soap_endpoint)
{
	char soap_action[] = "urn:dslforum-org:cwmp-1-1:GetRPCMethodsIn";

	struct __cwmp__GetRPCMethods soap_tmp___cwmp__GetRPCMethods;
	struct _cwmp__GetRPCMethodsResponse cwmp__GetRPCMethodsResponse;
	soap_default__cwmp__GetRPCMethodsResponse(soap, &cwmp__GetRPCMethodsResponse);
	soap_default___cwmp__GetRPCMethods(soap, &soap_tmp___cwmp__GetRPCMethods);
	soap->encodingStyle = NULL;
	if (!soap_get___cwmp__GetRPCMethods(soap, &soap_tmp___cwmp__GetRPCMethods, "-cwmp:GetRPCMethods", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __cwmp__GetRPCMethods(soap, soap_tmp___cwmp__GetRPCMethods.cwmp__GetRPCMethods, &cwmp__GetRPCMethodsResponse);
	if (soap->error)
		return soap->error;

	fprintf(stdout, "%s\n", __func__);
	
	soap_serializeheader(soap);
	soap_serialize__cwmp__GetRPCMethodsResponse(soap, &cwmp__GetRPCMethodsResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__cwmp__GetRPCMethodsResponse(soap, &cwmp__GetRPCMethodsResponse, "cwmp:GetRPCMethodsResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__cwmp__GetRPCMethodsResponse(soap, &cwmp__GetRPCMethodsResponse, "cwmp:GetRPCMethodsResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp__SetParameterValues(struct soap *soap, const char *soap_endpoint)
{
	char soap_action[] = "urn:dslforum-org:cwmp-1-1:SetParameterValuesIn";

	struct __cwmp__SetParameterValues soap_tmp___cwmp__SetParameterValues;
	struct _cwmp__SetParameterValuesResponse cwmp__SetParameterValuesResponse;
	soap_default__cwmp__SetParameterValuesResponse(soap, &cwmp__SetParameterValuesResponse);
	soap_default___cwmp__SetParameterValues(soap, &soap_tmp___cwmp__SetParameterValues);
	soap->encodingStyle = NULL;
	if (!soap_get___cwmp__SetParameterValues(soap, &soap_tmp___cwmp__SetParameterValues, "-cwmp:SetParameterValues", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __cwmp__SetParameterValues(soap, soap_tmp___cwmp__SetParameterValues.cwmp__SetParameterValues, &cwmp__SetParameterValuesResponse);
	if (soap->error)
		return soap->error;

	fprintf(stdout, "%s\n", __func__);
	
	soap_serializeheader(soap);
	soap_serialize__cwmp__SetParameterValuesResponse(soap, &cwmp__SetParameterValuesResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__cwmp__SetParameterValuesResponse(soap, &cwmp__SetParameterValuesResponse, "cwmp:SetParameterValuesResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__cwmp__SetParameterValuesResponse(soap, &cwmp__SetParameterValuesResponse, "cwmp:SetParameterValuesResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp__GetParameterValues(struct soap *soap, const char *soap_endpoint)
{
	char soap_action[] = "urn:dslforum-org:cwmp-1-1:GetParameterValuesIn";

	struct __cwmp__GetParameterValues soap_tmp___cwmp__GetParameterValues;
	struct _cwmp__GetParameterValuesResponse cwmp__GetParameterValuesResponse;
	soap_default__cwmp__GetParameterValuesResponse(soap, &cwmp__GetParameterValuesResponse);
	soap_default___cwmp__GetParameterValues(soap, &soap_tmp___cwmp__GetParameterValues);
	soap->encodingStyle = NULL;
	if (!soap_get___cwmp__GetParameterValues(soap, &soap_tmp___cwmp__GetParameterValues, "-cwmp:GetParameterValues", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __cwmp__GetParameterValues(soap, soap_tmp___cwmp__GetParameterValues.cwmp__GetParameterValues, &cwmp__GetParameterValuesResponse);
	if (soap->error)
		return soap->error;

	fprintf(stdout, "%s\n", __func__);
	
	soap_serializeheader(soap);
	soap_serialize__cwmp__GetParameterValuesResponse(soap, &cwmp__GetParameterValuesResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__cwmp__GetParameterValuesResponse(soap, &cwmp__GetParameterValuesResponse, "cwmp:GetParameterValuesResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__cwmp__GetParameterValuesResponse(soap, &cwmp__GetParameterValuesResponse, "cwmp:GetParameterValuesResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp__GetParameterNames(struct soap *soap, const char *soap_endpoint)
{
	char soap_action[] = "urn:dslforum-org:cwmp-1-1:GetParameterNamesIn";

	struct __cwmp__GetParameterNames soap_tmp___cwmp__GetParameterNames;
	struct _cwmp__GetParameterNamesResponse cwmp__GetParameterNamesResponse;
	soap_default__cwmp__GetParameterNamesResponse(soap, &cwmp__GetParameterNamesResponse);
	soap_default___cwmp__GetParameterNames(soap, &soap_tmp___cwmp__GetParameterNames);
	soap->encodingStyle = NULL;
	if (!soap_get___cwmp__GetParameterNames(soap, &soap_tmp___cwmp__GetParameterNames, "-cwmp:GetParameterNames", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __cwmp__GetParameterNames(soap, soap_tmp___cwmp__GetParameterNames.cwmp__GetParameterNames, &cwmp__GetParameterNamesResponse);
	if (soap->error)
		return soap->error;

	fprintf(stdout, "%s\n", __func__);
	
	soap_serializeheader(soap);
	soap_serialize__cwmp__GetParameterNamesResponse(soap, &cwmp__GetParameterNamesResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__cwmp__GetParameterNamesResponse(soap, &cwmp__GetParameterNamesResponse, "cwmp:GetParameterNamesResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__cwmp__GetParameterNamesResponse(soap, &cwmp__GetParameterNamesResponse, "cwmp:GetParameterNamesResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp__SetParameterAttributes(struct soap *soap, const char *soap_endpoint)
{
	char soap_action[] = "urn:dslforum-org:cwmp-1-1:SetParameterAttributesIn";

	struct __cwmp__SetParameterAttributes soap_tmp___cwmp__SetParameterAttributes;
	struct _cwmp__SetParameterAttributesResponse cwmp__SetParameterAttributesResponse;
	soap_default__cwmp__SetParameterAttributesResponse(soap, &cwmp__SetParameterAttributesResponse);
	soap_default___cwmp__SetParameterAttributes(soap, &soap_tmp___cwmp__SetParameterAttributes);
	soap->encodingStyle = NULL;
	if (!soap_get___cwmp__SetParameterAttributes(soap, &soap_tmp___cwmp__SetParameterAttributes, "-cwmp:SetParameterAttributes", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __cwmp__SetParameterAttributes(soap, soap_tmp___cwmp__SetParameterAttributes.cwmp__SetParameterAttributes, &cwmp__SetParameterAttributesResponse);
	if (soap->error)
		return soap->error;

	fprintf(stdout, "%s\n", __func__);
	
	soap_serializeheader(soap);
	soap_serialize__cwmp__SetParameterAttributesResponse(soap, &cwmp__SetParameterAttributesResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__cwmp__SetParameterAttributesResponse(soap, &cwmp__SetParameterAttributesResponse, "cwmp:SetParameterAttributesResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__cwmp__SetParameterAttributesResponse(soap, &cwmp__SetParameterAttributesResponse, "cwmp:SetParameterAttributesResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp__GetParameterAttributes(struct soap *soap, const char *soap_endpoint)
{
	char soap_action[] = "urn:dslforum-org:cwmp-1-1:GetParameterAttributesIn";

	struct __cwmp__GetParameterAttributes soap_tmp___cwmp__GetParameterAttributes;
	struct _cwmp__GetParameterAttributesResponse cwmp__GetParameterAttributesResponse;
	soap_default__cwmp__GetParameterAttributesResponse(soap, &cwmp__GetParameterAttributesResponse);
	soap_default___cwmp__GetParameterAttributes(soap, &soap_tmp___cwmp__GetParameterAttributes);
	soap->encodingStyle = NULL;
	if (!soap_get___cwmp__GetParameterAttributes(soap, &soap_tmp___cwmp__GetParameterAttributes, "-cwmp:GetParameterAttributes", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __cwmp__GetParameterAttributes(soap, soap_tmp___cwmp__GetParameterAttributes.cwmp__GetParameterAttributes, &cwmp__GetParameterAttributesResponse);
	if (soap->error)
		return soap->error;

	fprintf(stdout, "%s\n", __func__);
	
	soap_serializeheader(soap);
	soap_serialize__cwmp__GetParameterAttributesResponse(soap, &cwmp__GetParameterAttributesResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__cwmp__GetParameterAttributesResponse(soap, &cwmp__GetParameterAttributesResponse, "cwmp:GetParameterAttributesResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__cwmp__GetParameterAttributesResponse(soap, &cwmp__GetParameterAttributesResponse, "cwmp:GetParameterAttributesResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp__AddObject(struct soap *soap, const char *soap_endpoint)
{
	char soap_action[] = "urn:dslforum-org:cwmp-1-1:AddObjectIn";

	struct __cwmp__AddObject soap_tmp___cwmp__AddObject;
	struct _cwmp__AddObjectResponse cwmp__AddObjectResponse;
	soap_default__cwmp__AddObjectResponse(soap, &cwmp__AddObjectResponse);
	soap_default___cwmp__AddObject(soap, &soap_tmp___cwmp__AddObject);
	soap->encodingStyle = NULL;
	if (!soap_get___cwmp__AddObject(soap, &soap_tmp___cwmp__AddObject, "-cwmp:AddObject", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __cwmp__AddObject(soap, soap_tmp___cwmp__AddObject.cwmp__AddObject, &cwmp__AddObjectResponse);
	if (soap->error)
		return soap->error;

	fprintf(stdout, "%s\n", __func__);
	
	soap_serializeheader(soap);
	soap_serialize__cwmp__AddObjectResponse(soap, &cwmp__AddObjectResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__cwmp__AddObjectResponse(soap, &cwmp__AddObjectResponse, "cwmp:AddObjectResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__cwmp__AddObjectResponse(soap, &cwmp__AddObjectResponse, "cwmp:AddObjectResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp__DeleteObject(struct soap *soap, const char *soap_endpoint)
{
	char soap_action[] = "urn:dslforum-org:cwmp-1-1:DeleteObjectIn";

	struct __cwmp__DeleteObject soap_tmp___cwmp__DeleteObject;
	struct _cwmp__DeleteObjectResponse cwmp__DeleteObjectResponse;
	soap_default__cwmp__DeleteObjectResponse(soap, &cwmp__DeleteObjectResponse);
	soap_default___cwmp__DeleteObject(soap, &soap_tmp___cwmp__DeleteObject);
	soap->encodingStyle = NULL;
	if (!soap_get___cwmp__DeleteObject(soap, &soap_tmp___cwmp__DeleteObject, "-cwmp:DeleteObject", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __cwmp__DeleteObject(soap, soap_tmp___cwmp__DeleteObject.cwmp__DeleteObject, &cwmp__DeleteObjectResponse);
	if (soap->error)
		return soap->error;

	fprintf(stdout, "%s\n", __func__);
	
	soap_serializeheader(soap);
	soap_serialize__cwmp__DeleteObjectResponse(soap, &cwmp__DeleteObjectResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__cwmp__DeleteObjectResponse(soap, &cwmp__DeleteObjectResponse, "cwmp:DeleteObjectResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__cwmp__DeleteObjectResponse(soap, &cwmp__DeleteObjectResponse, "cwmp:DeleteObjectResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp__Download(struct soap *soap, const char *soap_endpoint)
{
	char soap_action[] = "urn:dslforum-org:cwmp-1-1:DownloadIn";

	struct __cwmp__Download soap_tmp___cwmp__Download;
	struct _cwmp__DownloadResponse cwmp__DownloadResponse;
	soap_default__cwmp__DownloadResponse(soap, &cwmp__DownloadResponse);
	soap_default___cwmp__Download(soap, &soap_tmp___cwmp__Download);
	soap->encodingStyle = NULL;
	if (!soap_get___cwmp__Download(soap, &soap_tmp___cwmp__Download, "-cwmp:Download", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __cwmp__Download(soap, soap_tmp___cwmp__Download.cwmp__Download, &cwmp__DownloadResponse);
	if (soap->error)
		return soap->error;

	fprintf(stdout, "%s\n", __func__);
	
	soap_serializeheader(soap);
	soap_serialize__cwmp__DownloadResponse(soap, &cwmp__DownloadResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__cwmp__DownloadResponse(soap, &cwmp__DownloadResponse, "cwmp:DownloadResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__cwmp__DownloadResponse(soap, &cwmp__DownloadResponse, "cwmp:DownloadResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp__Reboot(struct soap *soap, const char *soap_endpoint)
{
	char soap_action[] = "urn:dslforum-org:cwmp-1-1:RebootIn";

	struct __cwmp__Reboot soap_tmp___cwmp__Reboot;
	struct _cwmp__RebootResponse cwmp__RebootResponse;
	soap_default__cwmp__RebootResponse(soap, &cwmp__RebootResponse);
	soap_default___cwmp__Reboot(soap, &soap_tmp___cwmp__Reboot);
	soap->encodingStyle = NULL;
	if (!soap_get___cwmp__Reboot(soap, &soap_tmp___cwmp__Reboot, "-cwmp:Reboot", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __cwmp__Reboot(soap, soap_tmp___cwmp__Reboot.cwmp__Reboot, &cwmp__RebootResponse);
	if (soap->error)
		return soap->error;

	fprintf(stdout, "%s\n", __func__);
	
	soap_serializeheader(soap);
	soap_serialize__cwmp__RebootResponse(soap, &cwmp__RebootResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__cwmp__RebootResponse(soap, &cwmp__RebootResponse, "cwmp:RebootResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__cwmp__RebootResponse(soap, &cwmp__RebootResponse, "cwmp:RebootResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp__GetQueuedTransfers(struct soap *soap, const char *soap_endpoint)
{
	char soap_action[] = "urn:dslforum-org:cwmp-1-1:GetQueuedTransfersIn";

	struct __cwmp__GetQueuedTransfers soap_tmp___cwmp__GetQueuedTransfers;
	struct _cwmp__GetQueuedTransfersResponse cwmp__GetQueuedTransfersResponse;
	soap_default__cwmp__GetQueuedTransfersResponse(soap, &cwmp__GetQueuedTransfersResponse);
	soap_default___cwmp__GetQueuedTransfers(soap, &soap_tmp___cwmp__GetQueuedTransfers);
	soap->encodingStyle = NULL;
	if (!soap_get___cwmp__GetQueuedTransfers(soap, &soap_tmp___cwmp__GetQueuedTransfers, "-cwmp:GetQueuedTransfers", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __cwmp__GetQueuedTransfers(soap, soap_tmp___cwmp__GetQueuedTransfers.cwmp__GetQueuedTransfers, &cwmp__GetQueuedTransfersResponse);
	if (soap->error)
		return soap->error;

	fprintf(stdout, "%s\n", __func__);
	
	soap_serializeheader(soap);
	soap_serialize__cwmp__GetQueuedTransfersResponse(soap, &cwmp__GetQueuedTransfersResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__cwmp__GetQueuedTransfersResponse(soap, &cwmp__GetQueuedTransfersResponse, "cwmp:GetQueuedTransfersResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__cwmp__GetQueuedTransfersResponse(soap, &cwmp__GetQueuedTransfersResponse, "cwmp:GetQueuedTransfersResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp__ScheduleInform(struct soap *soap, const char *soap_endpoint)
{
	char soap_action[] = "urn:dslforum-org:cwmp-1-1:ScheduleInformIn";

	struct __cwmp__ScheduleInform soap_tmp___cwmp__ScheduleInform;
	struct _cwmp__ScheduleInformResponse cwmp__ScheduleInformResponse;
	soap_default__cwmp__ScheduleInformResponse(soap, &cwmp__ScheduleInformResponse);
	soap_default___cwmp__ScheduleInform(soap, &soap_tmp___cwmp__ScheduleInform);
	soap->encodingStyle = NULL;
	if (!soap_get___cwmp__ScheduleInform(soap, &soap_tmp___cwmp__ScheduleInform, "-cwmp:ScheduleInform", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __cwmp__ScheduleInform(soap, soap_tmp___cwmp__ScheduleInform.cwmp__ScheduleInform, &cwmp__ScheduleInformResponse);
	if (soap->error)
		return soap->error;

	fprintf(stdout, "%s\n", __func__);
	
	soap_serializeheader(soap);
	soap_serialize__cwmp__ScheduleInformResponse(soap, &cwmp__ScheduleInformResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__cwmp__ScheduleInformResponse(soap, &cwmp__ScheduleInformResponse, "cwmp:ScheduleInformResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__cwmp__ScheduleInformResponse(soap, &cwmp__ScheduleInformResponse, "cwmp:ScheduleInformResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp__SetVouchers(struct soap *soap, const char *soap_endpoint)
{
	char soap_action[] = "urn:dslforum-org:cwmp-1-1:SetVouchersIn";

	struct __cwmp__SetVouchers soap_tmp___cwmp__SetVouchers;
	struct _cwmp__SetVouchersResponse cwmp__SetVouchersResponse;
	soap_default__cwmp__SetVouchersResponse(soap, &cwmp__SetVouchersResponse);
	soap_default___cwmp__SetVouchers(soap, &soap_tmp___cwmp__SetVouchers);
	soap->encodingStyle = NULL;
	if (!soap_get___cwmp__SetVouchers(soap, &soap_tmp___cwmp__SetVouchers, "-cwmp:SetVouchers", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __cwmp__SetVouchers(soap, soap_tmp___cwmp__SetVouchers.cwmp__SetVouchers, &cwmp__SetVouchersResponse);
	if (soap->error)
		return soap->error;

	fprintf(stdout, "%s\n", __func__);
	
	soap_serializeheader(soap);
	soap_serialize__cwmp__SetVouchersResponse(soap, &cwmp__SetVouchersResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__cwmp__SetVouchersResponse(soap, &cwmp__SetVouchersResponse, "cwmp:SetVouchersResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__cwmp__SetVouchersResponse(soap, &cwmp__SetVouchersResponse, "cwmp:SetVouchersResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp__GetOptions(struct soap *soap, const char *soap_endpoint)
{
	char soap_action[] = "urn:dslforum-org:cwmp-1-1:GetOptionsIn";

	struct __cwmp__GetOptions soap_tmp___cwmp__GetOptions;
	struct _cwmp__GetOptionsResponse cwmp__GetOptionsResponse;
	soap_default__cwmp__GetOptionsResponse(soap, &cwmp__GetOptionsResponse);
	soap_default___cwmp__GetOptions(soap, &soap_tmp___cwmp__GetOptions);
	soap->encodingStyle = NULL;
	if (!soap_get___cwmp__GetOptions(soap, &soap_tmp___cwmp__GetOptions, "-cwmp:GetOptions", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __cwmp__GetOptions(soap, soap_tmp___cwmp__GetOptions.cwmp__GetOptions, &cwmp__GetOptionsResponse);
	if (soap->error)
		return soap->error;

	fprintf(stdout, "%s\n", __func__);
	
	soap_serializeheader(soap);
	soap_serialize__cwmp__GetOptionsResponse(soap, &cwmp__GetOptionsResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__cwmp__GetOptionsResponse(soap, &cwmp__GetOptionsResponse, "cwmp:GetOptionsResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__cwmp__GetOptionsResponse(soap, &cwmp__GetOptionsResponse, "cwmp:GetOptionsResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp__Upload(struct soap *soap, const char *soap_endpoint)
{
	char soap_action[] = "urn:dslforum-org:cwmp-1-1:UploadIn";

	struct __cwmp__Upload soap_tmp___cwmp__Upload;
	struct _cwmp__UploadResponse cwmp__UploadResponse;
	soap_default__cwmp__UploadResponse(soap, &cwmp__UploadResponse);
	soap_default___cwmp__Upload(soap, &soap_tmp___cwmp__Upload);
	soap->encodingStyle = NULL;
	if (!soap_get___cwmp__Upload(soap, &soap_tmp___cwmp__Upload, "-cwmp:Upload", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __cwmp__Upload(soap, soap_tmp___cwmp__Upload.cwmp__Upload, &cwmp__UploadResponse);
	if (soap->error)
		return soap->error;

	fprintf(stdout, "%s\n", __func__);
	
	soap_serializeheader(soap);
	soap_serialize__cwmp__UploadResponse(soap, &cwmp__UploadResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__cwmp__UploadResponse(soap, &cwmp__UploadResponse, "cwmp:UploadResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__cwmp__UploadResponse(soap, &cwmp__UploadResponse, "cwmp:UploadResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp__FactoryReset(struct soap *soap, const char *soap_endpoint)
{
	char soap_action[] = "urn:dslforum-org:cwmp-1-1:FactoryResetIn";

	struct __cwmp__FactoryReset soap_tmp___cwmp__FactoryReset;
	struct _cwmp__FactoryResetResponse cwmp__FactoryResetResponse;
	soap_default__cwmp__FactoryResetResponse(soap, &cwmp__FactoryResetResponse);
	soap_default___cwmp__FactoryReset(soap, &soap_tmp___cwmp__FactoryReset);
	soap->encodingStyle = NULL;
	if (!soap_get___cwmp__FactoryReset(soap, &soap_tmp___cwmp__FactoryReset, "-cwmp:FactoryReset", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __cwmp__FactoryReset(soap, soap_tmp___cwmp__FactoryReset.cwmp__FactoryReset, &cwmp__FactoryResetResponse);
	if (soap->error)
		return soap->error;

	fprintf(stdout, "%s\n", __func__);
	
	soap_serializeheader(soap);
	soap_serialize__cwmp__FactoryResetResponse(soap, &cwmp__FactoryResetResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__cwmp__FactoryResetResponse(soap, &cwmp__FactoryResetResponse, "cwmp:FactoryResetResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__cwmp__FactoryResetResponse(soap, &cwmp__FactoryResetResponse, "cwmp:FactoryResetResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp__GetAllQueuedTransfers(struct soap *soap, const char *soap_endpoint)
{
	char soap_action[] = "urn:dslforum-org:cwmp-1-1:GetAllQueuedTransfersIn";

	struct __cwmp__GetAllQueuedTransfers soap_tmp___cwmp__GetAllQueuedTransfers;
	struct _cwmp__GetAllQueuedTransfersResponse cwmp__GetAllQueuedTransfersResponse;
	soap_default__cwmp__GetAllQueuedTransfersResponse(soap, &cwmp__GetAllQueuedTransfersResponse);
	soap_default___cwmp__GetAllQueuedTransfers(soap, &soap_tmp___cwmp__GetAllQueuedTransfers);
	soap->encodingStyle = NULL;
	if (!soap_get___cwmp__GetAllQueuedTransfers(soap, &soap_tmp___cwmp__GetAllQueuedTransfers, "-cwmp:GetAllQueuedTransfers", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __cwmp__GetAllQueuedTransfers(soap, soap_tmp___cwmp__GetAllQueuedTransfers.cwmp__GetAllQueuedTransfers, &cwmp__GetAllQueuedTransfersResponse);
	if (soap->error)
		return soap->error;

	fprintf(stdout, "%s\n", __func__);
	
	soap_serializeheader(soap);
	soap_serialize__cwmp__GetAllQueuedTransfersResponse(soap, &cwmp__GetAllQueuedTransfersResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__cwmp__GetAllQueuedTransfersResponse(soap, &cwmp__GetAllQueuedTransfersResponse, "cwmp:GetAllQueuedTransfersResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__cwmp__GetAllQueuedTransfersResponse(soap, &cwmp__GetAllQueuedTransfersResponse, "cwmp:GetAllQueuedTransfersResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp__Fault(struct soap *soap)
{	struct __cwmp__Fault soap_tmp___cwmp__Fault;
	soap_default___cwmp__Fault(soap, &soap_tmp___cwmp__Fault);
	soap->encodingStyle = NULL;
	if (!soap_get___cwmp__Fault(soap, &soap_tmp___cwmp__Fault, "-cwmp:Fault", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __cwmp__Fault(soap, soap_tmp___cwmp__Fault.cwmp__Fault);
	if (soap->error)
		return soap->error;
	return soap_closesock(soap);
}

#ifdef __cplusplus
}
#endif

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapServer.c */
