/* soapClient.c
   Generated by gSOAP 2.8.5 from cwmp-1-1.h

Copyright(C) 2000-2011, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) soapClient.c ver 2.8.5 2011-12-14 07:04:19 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp__Inform(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__Inform *cwmp__Inform, struct _cwmp__InformResponse *cwmp__InformResponse)
{	struct __cwmp__Inform soap_tmp___cwmp__Inform;
	if (!soap_action)
		soap_action = "urn:dslforum-org:cwmp-1-1:informIn";
	soap->encodingStyle = NULL;
	soap_tmp___cwmp__Inform.cwmp__Inform = cwmp__Inform;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___cwmp__Inform(soap, &soap_tmp___cwmp__Inform);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___cwmp__Inform(soap, &soap_tmp___cwmp__Inform, "-cwmp:Inform", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___cwmp__Inform(soap, &soap_tmp___cwmp__Inform, "-cwmp:Inform", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!cwmp__InformResponse)
		return soap_closesock(soap);
	soap_default__cwmp__InformResponse(soap, cwmp__InformResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__cwmp__InformResponse(soap, cwmp__InformResponse, "cwmp:InformResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp__TransferComplete(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__TransferComplete *cwmp__TransferComplete, struct _cwmp__TransferCompleteResponse *cwmp__TransferCompleteResponse)
{	struct __cwmp__TransferComplete soap_tmp___cwmp__TransferComplete;
	if (!soap_action)
		soap_action = "urn:dslforum-org:cwmp-1-1:transferCompleteIn";
	soap->encodingStyle = NULL;
	soap_tmp___cwmp__TransferComplete.cwmp__TransferComplete = cwmp__TransferComplete;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___cwmp__TransferComplete(soap, &soap_tmp___cwmp__TransferComplete);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___cwmp__TransferComplete(soap, &soap_tmp___cwmp__TransferComplete, "-cwmp:TransferComplete", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___cwmp__TransferComplete(soap, &soap_tmp___cwmp__TransferComplete, "-cwmp:TransferComplete", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!cwmp__TransferCompleteResponse)
		return soap_closesock(soap);
	soap_default__cwmp__TransferCompleteResponse(soap, cwmp__TransferCompleteResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__cwmp__TransferCompleteResponse(soap, cwmp__TransferCompleteResponse, "cwmp:TransferCompleteResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp__AutonomousTransferComplete(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__AutonomousTransferComplete *cwmp__AutonomousTransferComplete, struct _cwmp__AutonomousTransferCompleteResponse *cwmp__AutonomousTransferCompleteResponse)
{	struct __cwmp__AutonomousTransferComplete soap_tmp___cwmp__AutonomousTransferComplete;
	if (!soap_action)
		soap_action = "urn:dslforum-org:cwmp-1-1:autonomousTransferCompleteIn";
	soap->encodingStyle = NULL;
	soap_tmp___cwmp__AutonomousTransferComplete.cwmp__AutonomousTransferComplete = cwmp__AutonomousTransferComplete;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___cwmp__AutonomousTransferComplete(soap, &soap_tmp___cwmp__AutonomousTransferComplete);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___cwmp__AutonomousTransferComplete(soap, &soap_tmp___cwmp__AutonomousTransferComplete, "-cwmp:AutonomousTransferComplete", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___cwmp__AutonomousTransferComplete(soap, &soap_tmp___cwmp__AutonomousTransferComplete, "-cwmp:AutonomousTransferComplete", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!cwmp__AutonomousTransferCompleteResponse)
		return soap_closesock(soap);
	soap_default__cwmp__AutonomousTransferCompleteResponse(soap, cwmp__AutonomousTransferCompleteResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__cwmp__AutonomousTransferCompleteResponse(soap, cwmp__AutonomousTransferCompleteResponse, "cwmp:AutonomousTransferCompleteResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp__Kicked(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__Kicked *cwmp__Kicked, struct _cwmp__KickedResponse *cwmp__KickedResponse)
{	struct __cwmp__Kicked soap_tmp___cwmp__Kicked;
	if (!soap_action)
		soap_action = "urn:dslforum-org:cwmp-1-1:kickedIn";
	soap->encodingStyle = NULL;
	soap_tmp___cwmp__Kicked.cwmp__Kicked = cwmp__Kicked;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___cwmp__Kicked(soap, &soap_tmp___cwmp__Kicked);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___cwmp__Kicked(soap, &soap_tmp___cwmp__Kicked, "-cwmp:Kicked", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___cwmp__Kicked(soap, &soap_tmp___cwmp__Kicked, "-cwmp:Kicked", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!cwmp__KickedResponse)
		return soap_closesock(soap);
	soap_default__cwmp__KickedResponse(soap, cwmp__KickedResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__cwmp__KickedResponse(soap, cwmp__KickedResponse, "cwmp:KickedResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp__RequestDownload(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__RequestDownload *cwmp__RequestDownload, struct _cwmp__RequestDownloadResponse *cwmp__RequestDownloadResponse)
{	struct __cwmp__RequestDownload soap_tmp___cwmp__RequestDownload;
	if (!soap_action)
		soap_action = "urn:dslforum-org:cwmp-1-1:requestDownloadIn";
	soap->encodingStyle = NULL;
	soap_tmp___cwmp__RequestDownload.cwmp__RequestDownload = cwmp__RequestDownload;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___cwmp__RequestDownload(soap, &soap_tmp___cwmp__RequestDownload);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___cwmp__RequestDownload(soap, &soap_tmp___cwmp__RequestDownload, "-cwmp:RequestDownload", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___cwmp__RequestDownload(soap, &soap_tmp___cwmp__RequestDownload, "-cwmp:RequestDownload", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!cwmp__RequestDownloadResponse)
		return soap_closesock(soap);
	soap_default__cwmp__RequestDownloadResponse(soap, cwmp__RequestDownloadResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__cwmp__RequestDownloadResponse(soap, cwmp__RequestDownloadResponse, "cwmp:RequestDownloadResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_send___cwmp__EmptyPost(struct soap *soap, const char *soap_endpoint)
{       const char soap_action[] = "";
        soap->encodingStyle = NULL;

        soap_begin(soap);
        soap_serializeheader(soap);

        if (soap_begin_count(soap) || soap_end_count(soap))
                return soap->error;
        if (soap_connect(soap, soap_endpoint, soap_action)
         || soap_end_send(soap))
                return soap_closesock(soap);
        return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_send___cwmp__Fault(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__Fault *cwmp__Fault)
{	struct __cwmp__Fault soap_tmp___cwmp__Fault;
	if (!soap_action)
		soap_action = "urn:dslforum-org:cwmp-1-1:faultIn";
	soap->encodingStyle = NULL;
	soap_tmp___cwmp__Fault.cwmp__Fault = cwmp__Fault;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___cwmp__Fault(soap, &soap_tmp___cwmp__Fault);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___cwmp__Fault(soap, &soap_tmp___cwmp__Fault, "-cwmp:Fault", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___cwmp__Fault(soap, &soap_tmp___cwmp__Fault, "-cwmp:Fault", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_recv___cwmp__Fault(struct soap *soap, struct __cwmp__Fault *_param_1)
{
	soap_default___cwmp__Fault(soap, _param_1);
	soap_begin(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get___cwmp__Fault(soap, _param_1, "-cwmp:Fault", NULL);
	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
		soap->error = SOAP_NO_METHOD;
	if (soap->error
	 || soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

#ifdef __cplusplus
}
#endif

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapClient.c */
