/* soapClient.c
   Generated by gSOAP 2.8.5 from cwmp-1-1.h

Copyright(C) 2000-2011, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) soapClient.c ver 2.8.5 2011-12-14 07:04:19 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp__GetRPCMethods(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__GetRPCMethods *cwmp__GetRPCMethods, struct _cwmp__GetRPCMethodsResponse *cwmp__GetRPCMethodsResponse)
{	struct __cwmp__GetRPCMethods soap_tmp___cwmp__GetRPCMethods;
	if (!soap_action)
		soap_action = "urn:dslforum-org:cwmp-1-1:getRPCMethodsIn";
	soap->encodingStyle = NULL;
	soap_tmp___cwmp__GetRPCMethods.cwmp__GetRPCMethods = cwmp__GetRPCMethods;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___cwmp__GetRPCMethods(soap, &soap_tmp___cwmp__GetRPCMethods);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___cwmp__GetRPCMethods(soap, &soap_tmp___cwmp__GetRPCMethods, "-cwmp:GetRPCMethods", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___cwmp__GetRPCMethods(soap, &soap_tmp___cwmp__GetRPCMethods, "-cwmp:GetRPCMethods", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!cwmp__GetRPCMethodsResponse)
		return soap_closesock(soap);
	soap_default__cwmp__GetRPCMethodsResponse(soap, cwmp__GetRPCMethodsResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__cwmp__GetRPCMethodsResponse(soap, cwmp__GetRPCMethodsResponse, "cwmp:GetRPCMethodsResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp__SetParameterValues(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__SetParameterValues *cwmp__SetParameterValues, struct _cwmp__SetParameterValuesResponse *cwmp__SetParameterValuesResponse)
{	struct __cwmp__SetParameterValues soap_tmp___cwmp__SetParameterValues;
	if (!soap_action)
		soap_action = "urn:dslforum-org:cwmp-1-1:setParameterValuesIn";
	soap->encodingStyle = NULL;
	soap_tmp___cwmp__SetParameterValues.cwmp__SetParameterValues = cwmp__SetParameterValues;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___cwmp__SetParameterValues(soap, &soap_tmp___cwmp__SetParameterValues);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___cwmp__SetParameterValues(soap, &soap_tmp___cwmp__SetParameterValues, "-cwmp:SetParameterValues", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___cwmp__SetParameterValues(soap, &soap_tmp___cwmp__SetParameterValues, "-cwmp:SetParameterValues", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!cwmp__SetParameterValuesResponse)
		return soap_closesock(soap);
	soap_default__cwmp__SetParameterValuesResponse(soap, cwmp__SetParameterValuesResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__cwmp__SetParameterValuesResponse(soap, cwmp__SetParameterValuesResponse, "cwmp:SetParameterValuesResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp__GetParameterValues(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__GetParameterValues *cwmp__GetParameterValues, struct _cwmp__GetParameterValuesResponse *cwmp__GetParameterValuesResponse)
{	struct __cwmp__GetParameterValues soap_tmp___cwmp__GetParameterValues;
	if (!soap_action)
		soap_action = "urn:dslforum-org:cwmp-1-1:getParameterValuesIn";
	soap->encodingStyle = NULL;
	soap_tmp___cwmp__GetParameterValues.cwmp__GetParameterValues = cwmp__GetParameterValues;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___cwmp__GetParameterValues(soap, &soap_tmp___cwmp__GetParameterValues);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___cwmp__GetParameterValues(soap, &soap_tmp___cwmp__GetParameterValues, "-cwmp:GetParameterValues", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___cwmp__GetParameterValues(soap, &soap_tmp___cwmp__GetParameterValues, "-cwmp:GetParameterValues", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!cwmp__GetParameterValuesResponse)
		return soap_closesock(soap);
	soap_default__cwmp__GetParameterValuesResponse(soap, cwmp__GetParameterValuesResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__cwmp__GetParameterValuesResponse(soap, cwmp__GetParameterValuesResponse, "cwmp:GetParameterValuesResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp__GetParameterNames(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__GetParameterNames *cwmp__GetParameterNames, struct _cwmp__GetParameterNamesResponse *cwmp__GetParameterNamesResponse)
{	struct __cwmp__GetParameterNames soap_tmp___cwmp__GetParameterNames;
	if (!soap_action)
		soap_action = "urn:dslforum-org:cwmp-1-1:getParameterNamesIn";
	soap->encodingStyle = NULL;
	soap_tmp___cwmp__GetParameterNames.cwmp__GetParameterNames = cwmp__GetParameterNames;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___cwmp__GetParameterNames(soap, &soap_tmp___cwmp__GetParameterNames);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___cwmp__GetParameterNames(soap, &soap_tmp___cwmp__GetParameterNames, "-cwmp:GetParameterNames", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___cwmp__GetParameterNames(soap, &soap_tmp___cwmp__GetParameterNames, "-cwmp:GetParameterNames", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!cwmp__GetParameterNamesResponse)
		return soap_closesock(soap);
	soap_default__cwmp__GetParameterNamesResponse(soap, cwmp__GetParameterNamesResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__cwmp__GetParameterNamesResponse(soap, cwmp__GetParameterNamesResponse, "cwmp:GetParameterNamesResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp__SetParameterAttributes(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__SetParameterAttributes *cwmp__SetParameterAttributes, struct _cwmp__SetParameterAttributesResponse *cwmp__SetParameterAttributesResponse)
{	struct __cwmp__SetParameterAttributes soap_tmp___cwmp__SetParameterAttributes;
	if (!soap_action)
		soap_action = "urn:dslforum-org:cwmp-1-1:setParameterAttributesIn";
	soap->encodingStyle = NULL;
	soap_tmp___cwmp__SetParameterAttributes.cwmp__SetParameterAttributes = cwmp__SetParameterAttributes;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___cwmp__SetParameterAttributes(soap, &soap_tmp___cwmp__SetParameterAttributes);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___cwmp__SetParameterAttributes(soap, &soap_tmp___cwmp__SetParameterAttributes, "-cwmp:SetParameterAttributes", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___cwmp__SetParameterAttributes(soap, &soap_tmp___cwmp__SetParameterAttributes, "-cwmp:SetParameterAttributes", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!cwmp__SetParameterAttributesResponse)
		return soap_closesock(soap);
	soap_default__cwmp__SetParameterAttributesResponse(soap, cwmp__SetParameterAttributesResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__cwmp__SetParameterAttributesResponse(soap, cwmp__SetParameterAttributesResponse, "cwmp:SetParameterAttributesResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp__GetParameterAttributes(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__GetParameterAttributes *cwmp__GetParameterAttributes, struct _cwmp__GetParameterAttributesResponse *cwmp__GetParameterAttributesResponse)
{	struct __cwmp__GetParameterAttributes soap_tmp___cwmp__GetParameterAttributes;
	if (!soap_action)
		soap_action = "urn:dslforum-org:cwmp-1-1:getParameterAttributesIn";
	soap->encodingStyle = NULL;
	soap_tmp___cwmp__GetParameterAttributes.cwmp__GetParameterAttributes = cwmp__GetParameterAttributes;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___cwmp__GetParameterAttributes(soap, &soap_tmp___cwmp__GetParameterAttributes);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___cwmp__GetParameterAttributes(soap, &soap_tmp___cwmp__GetParameterAttributes, "-cwmp:GetParameterAttributes", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___cwmp__GetParameterAttributes(soap, &soap_tmp___cwmp__GetParameterAttributes, "-cwmp:GetParameterAttributes", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!cwmp__GetParameterAttributesResponse)
		return soap_closesock(soap);
	soap_default__cwmp__GetParameterAttributesResponse(soap, cwmp__GetParameterAttributesResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__cwmp__GetParameterAttributesResponse(soap, cwmp__GetParameterAttributesResponse, "cwmp:GetParameterAttributesResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp__AddObject(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__AddObject *cwmp__AddObject, struct _cwmp__AddObjectResponse *cwmp__AddObjectResponse)
{	struct __cwmp__AddObject soap_tmp___cwmp__AddObject;
	if (!soap_action)
		soap_action = "urn:dslforum-org:cwmp-1-1:addObjectIn";
	soap->encodingStyle = NULL;
	soap_tmp___cwmp__AddObject.cwmp__AddObject = cwmp__AddObject;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___cwmp__AddObject(soap, &soap_tmp___cwmp__AddObject);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___cwmp__AddObject(soap, &soap_tmp___cwmp__AddObject, "-cwmp:AddObject", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___cwmp__AddObject(soap, &soap_tmp___cwmp__AddObject, "-cwmp:AddObject", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!cwmp__AddObjectResponse)
		return soap_closesock(soap);
	soap_default__cwmp__AddObjectResponse(soap, cwmp__AddObjectResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__cwmp__AddObjectResponse(soap, cwmp__AddObjectResponse, "cwmp:AddObjectResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp__DeleteObject(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__DeleteObject *cwmp__DeleteObject, struct _cwmp__DeleteObjectResponse *cwmp__DeleteObjectResponse)
{	struct __cwmp__DeleteObject soap_tmp___cwmp__DeleteObject;
	if (!soap_action)
		soap_action = "urn:dslforum-org:cwmp-1-1:deleteObjectIn";
	soap->encodingStyle = NULL;
	soap_tmp___cwmp__DeleteObject.cwmp__DeleteObject = cwmp__DeleteObject;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___cwmp__DeleteObject(soap, &soap_tmp___cwmp__DeleteObject);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___cwmp__DeleteObject(soap, &soap_tmp___cwmp__DeleteObject, "-cwmp:DeleteObject", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___cwmp__DeleteObject(soap, &soap_tmp___cwmp__DeleteObject, "-cwmp:DeleteObject", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!cwmp__DeleteObjectResponse)
		return soap_closesock(soap);
	soap_default__cwmp__DeleteObjectResponse(soap, cwmp__DeleteObjectResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__cwmp__DeleteObjectResponse(soap, cwmp__DeleteObjectResponse, "cwmp:DeleteObjectResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp__Download(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__Download *cwmp__Download, struct _cwmp__DownloadResponse *cwmp__DownloadResponse)
{	struct __cwmp__Download soap_tmp___cwmp__Download;
	if (!soap_action)
		soap_action = "urn:dslforum-org:cwmp-1-1:downloadIn";
	soap->encodingStyle = NULL;
	soap_tmp___cwmp__Download.cwmp__Download = cwmp__Download;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___cwmp__Download(soap, &soap_tmp___cwmp__Download);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___cwmp__Download(soap, &soap_tmp___cwmp__Download, "-cwmp:Download", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___cwmp__Download(soap, &soap_tmp___cwmp__Download, "-cwmp:Download", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!cwmp__DownloadResponse)
		return soap_closesock(soap);
	soap_default__cwmp__DownloadResponse(soap, cwmp__DownloadResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__cwmp__DownloadResponse(soap, cwmp__DownloadResponse, "cwmp:DownloadResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp__Reboot(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__Reboot *cwmp__Reboot, struct _cwmp__RebootResponse *cwmp__RebootResponse)
{	struct __cwmp__Reboot soap_tmp___cwmp__Reboot;
	if (!soap_action)
		soap_action = "urn:dslforum-org:cwmp-1-1:rebootIn";
	soap->encodingStyle = NULL;
	soap_tmp___cwmp__Reboot.cwmp__Reboot = cwmp__Reboot;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___cwmp__Reboot(soap, &soap_tmp___cwmp__Reboot);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___cwmp__Reboot(soap, &soap_tmp___cwmp__Reboot, "-cwmp:Reboot", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___cwmp__Reboot(soap, &soap_tmp___cwmp__Reboot, "-cwmp:Reboot", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!cwmp__RebootResponse)
		return soap_closesock(soap);
	soap_default__cwmp__RebootResponse(soap, cwmp__RebootResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__cwmp__RebootResponse(soap, cwmp__RebootResponse, "cwmp:RebootResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp__GetQueuedTransfers(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__GetQueuedTransfers *cwmp__GetQueuedTransfers, struct _cwmp__GetQueuedTransfersResponse *cwmp__GetQueuedTransfersResponse)
{	struct __cwmp__GetQueuedTransfers soap_tmp___cwmp__GetQueuedTransfers;
	if (!soap_action)
		soap_action = "urn:dslforum-org:cwmp-1-1:getQueuedTransfersIn";
	soap->encodingStyle = NULL;
	soap_tmp___cwmp__GetQueuedTransfers.cwmp__GetQueuedTransfers = cwmp__GetQueuedTransfers;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___cwmp__GetQueuedTransfers(soap, &soap_tmp___cwmp__GetQueuedTransfers);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___cwmp__GetQueuedTransfers(soap, &soap_tmp___cwmp__GetQueuedTransfers, "-cwmp:GetQueuedTransfers", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___cwmp__GetQueuedTransfers(soap, &soap_tmp___cwmp__GetQueuedTransfers, "-cwmp:GetQueuedTransfers", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!cwmp__GetQueuedTransfersResponse)
		return soap_closesock(soap);
	soap_default__cwmp__GetQueuedTransfersResponse(soap, cwmp__GetQueuedTransfersResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__cwmp__GetQueuedTransfersResponse(soap, cwmp__GetQueuedTransfersResponse, "cwmp:GetQueuedTransfersResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp__ScheduleInform(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__ScheduleInform *cwmp__ScheduleInform, struct _cwmp__ScheduleInformResponse *cwmp__ScheduleInformResponse)
{	struct __cwmp__ScheduleInform soap_tmp___cwmp__ScheduleInform;
	if (!soap_action)
		soap_action = "urn:dslforum-org:cwmp-1-1:scheduleInformIn";
	soap->encodingStyle = NULL;
	soap_tmp___cwmp__ScheduleInform.cwmp__ScheduleInform = cwmp__ScheduleInform;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___cwmp__ScheduleInform(soap, &soap_tmp___cwmp__ScheduleInform);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___cwmp__ScheduleInform(soap, &soap_tmp___cwmp__ScheduleInform, "-cwmp:ScheduleInform", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___cwmp__ScheduleInform(soap, &soap_tmp___cwmp__ScheduleInform, "-cwmp:ScheduleInform", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!cwmp__ScheduleInformResponse)
		return soap_closesock(soap);
	soap_default__cwmp__ScheduleInformResponse(soap, cwmp__ScheduleInformResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__cwmp__ScheduleInformResponse(soap, cwmp__ScheduleInformResponse, "cwmp:ScheduleInformResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp__SetVouchers(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__SetVouchers *cwmp__SetVouchers, struct _cwmp__SetVouchersResponse *cwmp__SetVouchersResponse)
{	struct __cwmp__SetVouchers soap_tmp___cwmp__SetVouchers;
	if (!soap_action)
		soap_action = "urn:dslforum-org:cwmp-1-1:setVouchersIn";
	soap->encodingStyle = NULL;
	soap_tmp___cwmp__SetVouchers.cwmp__SetVouchers = cwmp__SetVouchers;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___cwmp__SetVouchers(soap, &soap_tmp___cwmp__SetVouchers);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___cwmp__SetVouchers(soap, &soap_tmp___cwmp__SetVouchers, "-cwmp:SetVouchers", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___cwmp__SetVouchers(soap, &soap_tmp___cwmp__SetVouchers, "-cwmp:SetVouchers", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!cwmp__SetVouchersResponse)
		return soap_closesock(soap);
	soap_default__cwmp__SetVouchersResponse(soap, cwmp__SetVouchersResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__cwmp__SetVouchersResponse(soap, cwmp__SetVouchersResponse, "cwmp:SetVouchersResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp__GetOptions(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__GetOptions *cwmp__GetOptions, struct _cwmp__GetOptionsResponse *cwmp__GetOptionsResponse)
{	struct __cwmp__GetOptions soap_tmp___cwmp__GetOptions;
	if (!soap_action)
		soap_action = "urn:dslforum-org:cwmp-1-1:getOptionsIn";
	soap->encodingStyle = NULL;
	soap_tmp___cwmp__GetOptions.cwmp__GetOptions = cwmp__GetOptions;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___cwmp__GetOptions(soap, &soap_tmp___cwmp__GetOptions);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___cwmp__GetOptions(soap, &soap_tmp___cwmp__GetOptions, "-cwmp:GetOptions", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___cwmp__GetOptions(soap, &soap_tmp___cwmp__GetOptions, "-cwmp:GetOptions", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!cwmp__GetOptionsResponse)
		return soap_closesock(soap);
	soap_default__cwmp__GetOptionsResponse(soap, cwmp__GetOptionsResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__cwmp__GetOptionsResponse(soap, cwmp__GetOptionsResponse, "cwmp:GetOptionsResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp__Upload(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__Upload *cwmp__Upload, struct _cwmp__UploadResponse *cwmp__UploadResponse)
{	struct __cwmp__Upload soap_tmp___cwmp__Upload;
	if (!soap_action)
		soap_action = "urn:dslforum-org:cwmp-1-1:uploadIn";
	soap->encodingStyle = NULL;
	soap_tmp___cwmp__Upload.cwmp__Upload = cwmp__Upload;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___cwmp__Upload(soap, &soap_tmp___cwmp__Upload);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___cwmp__Upload(soap, &soap_tmp___cwmp__Upload, "-cwmp:Upload", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___cwmp__Upload(soap, &soap_tmp___cwmp__Upload, "-cwmp:Upload", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!cwmp__UploadResponse)
		return soap_closesock(soap);
	soap_default__cwmp__UploadResponse(soap, cwmp__UploadResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__cwmp__UploadResponse(soap, cwmp__UploadResponse, "cwmp:UploadResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp__FactoryReset(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__FactoryReset *cwmp__FactoryReset, struct _cwmp__FactoryResetResponse *cwmp__FactoryResetResponse)
{	struct __cwmp__FactoryReset soap_tmp___cwmp__FactoryReset;
	if (!soap_action)
		soap_action = "urn:dslforum-org:cwmp-1-1:factoryResetIn";
	soap->encodingStyle = NULL;
	soap_tmp___cwmp__FactoryReset.cwmp__FactoryReset = cwmp__FactoryReset;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___cwmp__FactoryReset(soap, &soap_tmp___cwmp__FactoryReset);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___cwmp__FactoryReset(soap, &soap_tmp___cwmp__FactoryReset, "-cwmp:FactoryReset", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___cwmp__FactoryReset(soap, &soap_tmp___cwmp__FactoryReset, "-cwmp:FactoryReset", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!cwmp__FactoryResetResponse)
		return soap_closesock(soap);
	soap_default__cwmp__FactoryResetResponse(soap, cwmp__FactoryResetResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__cwmp__FactoryResetResponse(soap, cwmp__FactoryResetResponse, "cwmp:FactoryResetResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp__GetAllQueuedTransfers(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__GetAllQueuedTransfers *cwmp__GetAllQueuedTransfers, struct _cwmp__GetAllQueuedTransfersResponse *cwmp__GetAllQueuedTransfersResponse)
{	struct __cwmp__GetAllQueuedTransfers soap_tmp___cwmp__GetAllQueuedTransfers;
	if (!soap_action)
		soap_action = "urn:dslforum-org:cwmp-1-1:getAllQueuedTransfersIn";
	soap->encodingStyle = NULL;
	soap_tmp___cwmp__GetAllQueuedTransfers.cwmp__GetAllQueuedTransfers = cwmp__GetAllQueuedTransfers;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___cwmp__GetAllQueuedTransfers(soap, &soap_tmp___cwmp__GetAllQueuedTransfers);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___cwmp__GetAllQueuedTransfers(soap, &soap_tmp___cwmp__GetAllQueuedTransfers, "-cwmp:GetAllQueuedTransfers", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___cwmp__GetAllQueuedTransfers(soap, &soap_tmp___cwmp__GetAllQueuedTransfers, "-cwmp:GetAllQueuedTransfers", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!cwmp__GetAllQueuedTransfersResponse)
		return soap_closesock(soap);
	soap_default__cwmp__GetAllQueuedTransfersResponse(soap, cwmp__GetAllQueuedTransfersResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__cwmp__GetAllQueuedTransfersResponse(soap, cwmp__GetAllQueuedTransfersResponse, "cwmp:GetAllQueuedTransfersResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp__Inform(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__Inform *cwmp__Inform, struct _cwmp__InformResponse *cwmp__InformResponse)
{	struct __cwmp__Inform soap_tmp___cwmp__Inform;
	if (!soap_action)
		soap_action = "urn:dslforum-org:cwmp-1-1:informIn";
	soap->encodingStyle = NULL;
	soap_tmp___cwmp__Inform.cwmp__Inform = cwmp__Inform;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___cwmp__Inform(soap, &soap_tmp___cwmp__Inform);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___cwmp__Inform(soap, &soap_tmp___cwmp__Inform, "-cwmp:Inform", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___cwmp__Inform(soap, &soap_tmp___cwmp__Inform, "-cwmp:Inform", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!cwmp__InformResponse)
		return soap_closesock(soap);
	soap_default__cwmp__InformResponse(soap, cwmp__InformResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__cwmp__InformResponse(soap, cwmp__InformResponse, "cwmp:InformResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp__TransferComplete(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__TransferComplete *cwmp__TransferComplete, struct _cwmp__TransferCompleteResponse *cwmp__TransferCompleteResponse)
{	struct __cwmp__TransferComplete soap_tmp___cwmp__TransferComplete;
	if (!soap_action)
		soap_action = "urn:dslforum-org:cwmp-1-1:transferCompleteIn";
	soap->encodingStyle = NULL;
	soap_tmp___cwmp__TransferComplete.cwmp__TransferComplete = cwmp__TransferComplete;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___cwmp__TransferComplete(soap, &soap_tmp___cwmp__TransferComplete);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___cwmp__TransferComplete(soap, &soap_tmp___cwmp__TransferComplete, "-cwmp:TransferComplete", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___cwmp__TransferComplete(soap, &soap_tmp___cwmp__TransferComplete, "-cwmp:TransferComplete", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!cwmp__TransferCompleteResponse)
		return soap_closesock(soap);
	soap_default__cwmp__TransferCompleteResponse(soap, cwmp__TransferCompleteResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__cwmp__TransferCompleteResponse(soap, cwmp__TransferCompleteResponse, "cwmp:TransferCompleteResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp__AutonomousTransferComplete(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__AutonomousTransferComplete *cwmp__AutonomousTransferComplete, struct _cwmp__AutonomousTransferCompleteResponse *cwmp__AutonomousTransferCompleteResponse)
{	struct __cwmp__AutonomousTransferComplete soap_tmp___cwmp__AutonomousTransferComplete;
	if (!soap_action)
		soap_action = "urn:dslforum-org:cwmp-1-1:autonomousTransferCompleteIn";
	soap->encodingStyle = NULL;
	soap_tmp___cwmp__AutonomousTransferComplete.cwmp__AutonomousTransferComplete = cwmp__AutonomousTransferComplete;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___cwmp__AutonomousTransferComplete(soap, &soap_tmp___cwmp__AutonomousTransferComplete);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___cwmp__AutonomousTransferComplete(soap, &soap_tmp___cwmp__AutonomousTransferComplete, "-cwmp:AutonomousTransferComplete", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___cwmp__AutonomousTransferComplete(soap, &soap_tmp___cwmp__AutonomousTransferComplete, "-cwmp:AutonomousTransferComplete", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!cwmp__AutonomousTransferCompleteResponse)
		return soap_closesock(soap);
	soap_default__cwmp__AutonomousTransferCompleteResponse(soap, cwmp__AutonomousTransferCompleteResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__cwmp__AutonomousTransferCompleteResponse(soap, cwmp__AutonomousTransferCompleteResponse, "cwmp:AutonomousTransferCompleteResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp__Kicked(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__Kicked *cwmp__Kicked, struct _cwmp__KickedResponse *cwmp__KickedResponse)
{	struct __cwmp__Kicked soap_tmp___cwmp__Kicked;
	if (!soap_action)
		soap_action = "urn:dslforum-org:cwmp-1-1:kickedIn";
	soap->encodingStyle = NULL;
	soap_tmp___cwmp__Kicked.cwmp__Kicked = cwmp__Kicked;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___cwmp__Kicked(soap, &soap_tmp___cwmp__Kicked);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___cwmp__Kicked(soap, &soap_tmp___cwmp__Kicked, "-cwmp:Kicked", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___cwmp__Kicked(soap, &soap_tmp___cwmp__Kicked, "-cwmp:Kicked", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!cwmp__KickedResponse)
		return soap_closesock(soap);
	soap_default__cwmp__KickedResponse(soap, cwmp__KickedResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__cwmp__KickedResponse(soap, cwmp__KickedResponse, "cwmp:KickedResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp__RequestDownload(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__RequestDownload *cwmp__RequestDownload, struct _cwmp__RequestDownloadResponse *cwmp__RequestDownloadResponse)
{	struct __cwmp__RequestDownload soap_tmp___cwmp__RequestDownload;
	if (!soap_action)
		soap_action = "urn:dslforum-org:cwmp-1-1:requestDownloadIn";
	soap->encodingStyle = NULL;
	soap_tmp___cwmp__RequestDownload.cwmp__RequestDownload = cwmp__RequestDownload;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___cwmp__RequestDownload(soap, &soap_tmp___cwmp__RequestDownload);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___cwmp__RequestDownload(soap, &soap_tmp___cwmp__RequestDownload, "-cwmp:RequestDownload", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___cwmp__RequestDownload(soap, &soap_tmp___cwmp__RequestDownload, "-cwmp:RequestDownload", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!cwmp__RequestDownloadResponse)
		return soap_closesock(soap);
	soap_default__cwmp__RequestDownloadResponse(soap, cwmp__RequestDownloadResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__cwmp__RequestDownloadResponse(soap, cwmp__RequestDownloadResponse, "cwmp:RequestDownloadResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_send___cwmp__EmptyPost(struct soap *soap, const char *soap_endpoint)
{       const char soap_action[] = "";
        soap->encodingStyle = NULL;

        soap_begin(soap);
        soap_serializeheader(soap);

        if (soap_begin_count(soap) || soap_end_count(soap))
                return soap->error;
        if (soap_connect(soap, soap_endpoint, soap_action)
         || soap_end_send(soap))
                return soap_closesock(soap);
        return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_send___cwmp__Fault(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__Fault *cwmp__Fault)
{	struct __cwmp__Fault soap_tmp___cwmp__Fault;
	if (!soap_action)
		soap_action = "urn:dslforum-org:cwmp-1-1:faultIn";
	soap->encodingStyle = NULL;
	soap_tmp___cwmp__Fault.cwmp__Fault = cwmp__Fault;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___cwmp__Fault(soap, &soap_tmp___cwmp__Fault);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___cwmp__Fault(soap, &soap_tmp___cwmp__Fault, "-cwmp:Fault", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___cwmp__Fault(soap, &soap_tmp___cwmp__Fault, "-cwmp:Fault", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_recv___cwmp__Fault(struct soap *soap, struct __cwmp__Fault *_param_1)
{
	soap_default___cwmp__Fault(soap, _param_1);
	soap_begin(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get___cwmp__Fault(soap, _param_1, "-cwmp:Fault", NULL);
	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
		soap->error = SOAP_NO_METHOD;
	if (soap->error
	 || soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

#ifdef __cplusplus
}
#endif

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapClient.c */
